### ISSUE TITLE
adaptive vertico-count

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#106]
It would be nice if user-initiated changes to the mini-buffer size (e.g. `M 10 C-x ^` or dragging the mode-line with mouse) temporarily changed the `vertico-count`.  Sometimes you need just a bit more room.

**Comment by minad** [comment]
Good idea as an extension. I don't want to add this to the main Vertico package. Unfortunately the resizing itself is just problematic by itself, see for example the recent #105.

**Comment by jdtsmith** [comment]
I don't know that this really makes sense as a standalone extension.  I mocked up something simple which works surprisingly well (in `vertico--setup`):

```elisp
  (if vertico--count-default
      (setq vertico-count vertico--count-default)
    (setq vertico--count-default vertico-count))
  (add-hook 'window-size-change-functions
	    (lambda (win)
	      (let ((height (window-height win)))
		(when (/= (1- height) vertico-count)
		  (setq vertico-count (1- height))
		  (vertico--exhibit))))
	    t t)
```

You can only resize larger when the minibuffer is _full_, but that'd be typically desired I suspect.  Reverts to the default value the next time around.  I suppose this could just advise `vertico--setup`.  But cleaner would be to switch to a `vertico--count` internally and reset that from the custom `vertico-count` variable at each setup.

**Comment by minad** [comment]
> I don't know that this really makes sense as a standalone extension. 

Maybe, but for now I am not interested in adding any kind of complication to Vertico itself at least for the near future. I will only add bugfixes or maybe crucial features, if it turns out that they are missing. You will have a hard time to convince me regarding features which I don't consider important. So I suggest you keep this in your private config for now. Maybe my opinion on this changes later. The patch you are proposing here is limited and small - so I don't exclude that this is added at some point.

**Comment by jdtsmith** [comment]
See extension PR #107.
