### ISSUE TITLE
How to stop vertico-buffer from affecting cursor shape

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/vertico#114]
I use evil and I have a setup where I have cursors of different shapes and colors depending on the state.

```elisp
(defhook! setup-cursor (evil-mode-hook)
  "Initialize the default cursor shape and size."
  (setq evil-insert-state-cursor   '((bar . 3)   "chartreuse3"))
  (setq evil-emacs-state-cursor    '((bar . 3)   "SkyBlue2"))
  (setq evil-normal-state-cursor   '( box        "DarkGoldenrod2"))
  (setq evil-visual-state-cursor   '((hollow)    "dark gray"))
  (setq evil-operator-state-cursor '((hbar . 10) "hot pink"))
  (setq evil-replace-state-cursor  '( box        "chocolate"))
  (setq evil-motion-state-cursor   '( box        "plum3")))
```
For consistency I have it such that the cursor is in insert state while I'm in the minibuffer since I'm inserting text:

```elisp
(defvar oo-evil-state-before-minibuffer nil
  "Store the evil state before entering the minibuffer.")

(defhook! preserve-prior-evil-state (minibuffer-setup-hook)
  "Save state before entering the minibuffer and enter insert state."
  (when (bound-and-true-p evil-mode)
    (setq oo-evil-state-before-minibuffer evil-state)
    (evil-insert-state)))

(defhook! restore-prior-evil-state (minibuffer-exit-hook)
  "Restore state after minibuffer."
  (when (bound-and-true-p evil-mode)
    (evil-change-state oo-evil-state-before-minibuffer)
    (setq oo-evil-state-before-minibuffer nil)))
```
This works when using the minibuffer (e.g. the insert state cursor is displayed), but not with `vertico-buffer-mode` enabled. The cursor color is correct but the shape is wrong. Perhaps, this has to do with `vertico--setup` which sets the cursor-type to `(bar . 0)`.

**Comment by minad** [comment]
This is not easily possible. `vertico-buffer` necessarily has to manipulate the cursor shape since the actual focus stays inside the minibuffer. `vertico-buffer` adjusts the settings such that the focus appears to be in the `*Vertico*` buffer. Maybe we could add some configuration variables or tweaks to fix your issue.

**Comment by kmontag** [comment]
For anyone stumbling across this, I was able to get my normal cursor behavior in the vertico buffer using:

```
(advice-add
  'vertico-buffer--redisplay
  :after
  (lambda (&rest _)
    (when (eq (selected-window) (active-minibuffer-window))
      (setq-local cursor-in-non-selected-windows cursor-type))))
```

With this, my vertico buffer correctly tracks the appearance of the "real" cursor in the minibuffer (in my case based on the `evil-state`).

@minad might it make sense to add this as default behavior, rather than the hardcoded `box` cursor? It seems like a pretty generic fix, though I'm admittedly not too familiar with the internals or edge cases here.

**Comment by minad** [comment]
@kmontag Pushed a fix. Thanks for revisiting this old issue. Please check if it works properly for you.

**Comment by kmontag** [comment]
@minad yep, that fixes it for me :) thanks!
