### ISSUE TITLE
Bottom candidates are cut off

### ISSUE THREAD

**Issue by Koekelas** [minad/vertico#14]
When the candidate's height is higher than the default's height, the bottom candidates are cut off. Notice that, when running `consult-outline` in an Org buffer with three headings, Vertico only shows two:

![image](https://user-images.githubusercontent.com/6143998/114580012-c03d7e80-9c7e-11eb-9b08-4b2da843fe13.png)

This is particularly annoying as one can't see what one selects. This doesn't seem related to other (closed) issues regarding minibuffer height. Thank you in advance.

- Emacs 27.2
- vertico 0.4
- `resize-mini-windows` set to `t`
- `vertico-count` left to `10`

**Comment by Koekelas** [comment]
With db68f67 and the above scenario, there's some empty space after the last candidate but at least all candidates are visible! Thank you for the speedy fix.

**Comment by minad** [comment]
@Koekelas The grow/shrinking behavior can be set by adjusting `resize-mini-windows`. This setting is respected by Vertico. If you set it to `t` it will also shrink. 

But it could be that you observe a small empty space, this happens since I am rounding to the default line height.  I do that since I use `consult-buffer` and the buffer grouping with reduced line heights for the grouping separators. Without the rounding the window size would jiggle.

![buffer](https://user-images.githubusercontent.com/50754/114597305-e5d38380-9c90-11eb-972a-bd957778b4b4.png)

**Comment by Koekelas** [comment]
In other words, it's by design. Thank you for the clarification.

**Comment by minad** [comment]
Yes, and a bit biased for my needs. But resizing by default line height  well with the retro look of the Emacs UI ;) 

But seriously I think this is a good compromise since most commands don't generate candidates with fancy/larger faces. If you want to you can play around with `vertico--display-candidates` and modify how the resizing happens. Maybe you find something which works better for you. But maybe you are not too much disturbed by the small whitespace?

**Comment by Koekelas** [comment]
What is old will be new once more. I find it much easier to accept something when I understand the reasoning behind it. Besides, this is Emacs after all, everything is just an advice away. When I every run out of more "pressing" things to tweak, I'll know what to do. Thanks again.
