### ISSUE TITLE
Why only one command history is displayed in Vertico?

### ISSUE THREAD

**Issue by e190** [minad/vertico#158]
[https://github.com/DarwinAwardWinner/amx/issues/46](url)
![图片](https://user-images.githubusercontent.com/39932163/141244143-4d04d0f3-8454-48d9-bbbd-5d3fb75edc00.png)
No matter how I use the command, only the first one is the history I used, okay
From the second command onwards it was not a command I had used

The amx configuration has not changed，I have no problem changing the backend to Ivy or Selectrum。
You can write something like this in.emacs files：

(add-to-list 'load-path "<path-to-vertico>")
(add-to-list 'load-path "<path-to-amx>")
(add-to-list 'load-path "<path-to-s>")
(require 'vertico)
(require 's)
(require 'amx)
(vertico-mode)
(amx-mode 1)

**Comment by minad** [comment]
Amx is not needed if you use Vertico. Vertico sorts by history position out of the box. If you save the history using `savehist-mode`, the history will even survive Emacs restarts. Furthermore you may be interested in Marginalia, which adds rich annotations to M-x and many other commands. As far as I can tell, Amx offers no benefits over these features. But I'd be happy to be corrected here.

If you still want to use Amx, please ask the author of Amx about this issue since it is not a Vertico issue. My assumption is that Amx should work in principle with Vertico, since Vertico is only a thin layer over the default completion system.
