### ISSUE TITLE
Is exclusion of `.git` directory intentional?

### ISSUE THREAD

**Issue by mcfarljm** [minad/vertico#159]
Have noticed that when using `find-file` in a directory that includes a `.git` directory, `.git` is not shown as a candidate.  It's still possible to navigate into it, but the completion behavior seems to depend on what else is in the directory.  In a directory where `.git` is the only item with "git" in the name, what I see is that `.git` does not appear in the initial completion list, but it will complete e.g. by typing "git".  On the other hand, in a directory with other items with "git" in the name (e.g., `.github` or `.gitignore`), then `.git` is neither in the initial completion list nor will it complete -- seems to be necessary to type ".git/" to navigate into it.

Just curious if this is by design  or possibly related to some settings (haven't noticed this behavior in other completion systems).

**Comment by minad** [comment]
Yes, it is intentional. The hidden directories/files are only shown if no visible directories/files match your input. You can configure the variable `completion-ignored-extensions`. It is also possible to disable the filtering completely:

~~~ elisp
(advice-add #'vertico--filter-files :override #'identity)
~~~
