### ISSUE TITLE
Is there a way to only start show candidates after at least one char input?

### ISSUE THREAD

**Issue by zhishi** [minad/vertico#166]
When I try to find variables or functions, usually I already have the partial name in mind, but vertico will show all candidates before I input any character, which is kind of slow (takes more than 1 second to show mini buffer), there are more than 10000+ candidates for variables, I guess some sorting is happening makes things even worse. 

I guess there is some way to trigger vertico only when input is not empty, but my knowledge of elisp and packages is very limited so I can't figure out where to start. Any help is appreciated. 

Ideally before any input I would like it only show recently used history rather than all candidates, which I think will be much faster on performance and still very useful. Or just show top N (configurable) candidates depends on the order function, if that can also improve performance.

**Comment by minad** [comment]
> When I try to find variables or functions, usually I already have the partial name in mind, but vertico will show all candidates before I input any character, which is kind of slow (takes more than 1 second to show mini buffer), there are more than 10000+ candidates for variables, I guess some sorting is happening makes things even worse.

For 20000 items it should not take 1s to show the candidates. For example the following is still very fast. Can you please try this snippet?

~~~ elisp
(defvar test-list nil)
(dotimes (i 20000)
  (push (md5 (format "%s" i)) test-list))
(completing-read "Prompt: " test-list)
~~~

If I crank up the number to 50000 it becomes noticeably slower on my system (Emacs 27.1, not the fastest system). But 20000 items should not be a problem. Also the sorting in Vertico is very fast, since I use a bucket sorting which pushes the complexity down if the candidates are uniformly distributed. 

However if I recall correctly there is one issue on Emacs 27.1, where `describe-variable` has an expensive completion predicate. The predicate was the bottleneck. This has been improved on Emacs 28. Which Emacs version do you use? Is your system particularly underpowered? I am not saying that Vertico should not work well on old systems - it should! But it helps me to understand your scenario a bit better.

There is one simple workaround. You can add a redisplay before Vertico initialization. This will show the prompt immediately such that you get visual feedback right away. You can then start typing right away. The candidates are computed, but the candidate computation is interruptible, so the responsiveness of the prompt will not be affected.

~~~ elisp
(advice-add #'vertico--setup :before #'redisplay)
~~~

I don't have such a redisplay in Vertico by default since it leads to flicker for fast commands. Most commands are very fast for me so this would degrade the UI experience. Another solution would be to add a limiter such that a minimal input is required as you suggested, but it is probably not necessary and it would also affect all commands (also the very fast ones). All that should be needed is the redisplay. The problem is that I don't see a possibility to determine beforehand if the redisplay is needed or not since I don't know early enough if the completion table will return 1000 or 100000 candidates.

> Ideally before any input I would like it only show recently used history rather than all candidates, which I think will be much faster on performance and still very useful. 

Only showing the candidates from history would be a significant deviation from the usual behavior. I don't want to add such a special casing to Vertico.

> Or just show top N (configurable) candidates depends on the order function, if that can also improve performance.

This is not possible since we have to first compute all candidates and sort to determine the top N candidates.

**Comment by zhishi** [comment]
Thanks for the suggestion and explanations, that's very helpful! To give you some contexts, I'm using Emacs 27.1 on a 2018 MacBook pro with 2.6 GHz 6-Core Intel Core i7, which I think pretty fast. `describe-variable` indeed is the slowest command, but I also feel a little delay on M-x (7000+ candidates) comparing with switch buffer (1000+ candidates) which is very fast.   

I tried the code snippet, as you said it showed immediately, even with 50000 there is just a little bit delay. So I guess the problem is the candidates generation logic rather than Vertico. I also tried redisplay which works but as your said after I input it still has a delay to refresh the list. 

It's not a serious problem anyway, I just feel there should be a way to limit candidates size. In general we can't assume input is always reasonable, so adding some throttling or defensive logic always better. And showing 10000+ candidates is not really useful before narrowing down.

**Comment by minad** [comment]
> So I guess the problem is the candidates generation logic rather than Vertico. 

Yes, in the case of `describe-variable` it is the slow completion predicate (fortunately fixed on Emacs 28). M-x also has a completion predicate, but it should not be as bad. You can run the profiler if you want to investigate the bottleneck.

> I also tried redisplay which works but as your said after I input it still has a delay to refresh the list.

Okay. Sure there is a delay until the computation finished but you can continue typing. The responsiveness of the input is not affected. As soon as you typed more letters the candidate display update will happen immediately. But the situation would not change if we add a minimum character input of for example 1. Then as soon as you type a single character you would also get the delay.

> It's not a serious problem anyway, I just feel there should be a way to limit candidates size. 

We could add this, but in my experience for all commands I am using it is fast enough. And since the candidate computation is interruptible there is no loss of responsiveness. If we introduce a fixed minimum candidate limit the behavior would not be better.

> In general we can't assume input is always reasonable, so adding some throttling or defensive logic always better. 

I disagree. The problem is this - adding throttling logic makes the behavior worse for fast commands. The price of this behavior is that we get a startup delay.

> And showing 10000+ candidates is not really useful before narrowing down.

Agree. The problem is that we don't know beforehand if we have a command which produces too many candidates. This means the limiting logic would require a per-command configuration or per-category configuration.

But you can experiment with such a limit. Try the following code snippet:

~~~ elisp
(defun vertico--limit (&rest app)
  (when (or (consp vertico--input)
            (> (- (point-max) (minibuffer-prompt-end)) 2))
    (apply app)))

(advice-add #'vertico--update-candidates :around #'vertico--limit)
~~~

**Comment by zhishi** [comment]
That code snippet works pretty well for my case, I just like the experience without any delay. But I also understand there is no perfect solution for this problem since we can't predict the number before calling the command. And if i delete chars in minibuffer it will encounter the slow problem again since candidates increased.

Still thanks for your help, at least I have some code to work around now. I'll close this issue.
