### ISSUE TITLE
(feature request) Extending vertico-repeat for N latest searches

### ISSUE THREAD

**Issue by linkenneth** [minad/vertico#182]
@minad , thanks for all your work on vertico.

I use `vertico-repeat` from Doom Emacs and it's been very useful, but one thing I find missing is the ability to resurrect a search a few searches back. In Doom Emacs, `vertico` is used for a *lot* of things by default, triggering any command such as finding a file will, for example, overwrite the last project-wide grep I did when using `vertico-repeat`.

What would be great is if numeric-prefixing `vertico-repeat` will repeat the search from N searches ago. Ideally, the number of searches saved would be customizable by a setting, but even the ability to go back 3-5 searches would be great.

**Comment by minad** [comment]
I doubt that using the prefix argument will lead to a good UI. But a completing-read interface for the last searches could work out, which allows you to select from the last searches. However overall I don't want to encourage such repeat-based workflows, since there are better existing alternatives. You can use the regular minibuffer history and in case you want to repeat a search multiple times you should rather embark-collect/export the search results. Personally I don't use vertico-repeat. I don't plan to add this for those reasons myself. But I would accept a PR, which implements a completing-read interface which allows you to select from `command input` pairs. `vertico-repeat` could open the completing-read when a prefix is given. But for better visibility I suggest to use a separate command, such that we end up with separate `vertico-repeat-last` and `vertico-repeat-history` commands (or select/complete if you prefer that bikeshed color).

**Comment by linkenneth** [comment]
@minad I'm considering implementing this. What is your workflow with minibuffer history though? I haven't been able to find something smooth with what's available to me.

**Comment by minad** [comment]
For some commands like `consult-grep` the minibuffer history stores the last input, so you can use `previous-history-element` to restart the last search. But for most commands the minibuffer stores the last selected candidate and not the input. This is where `vertico-repeat` comes into play or a potential `vertico-repeat-history`, which I proposed in my previous comment. However my preferred workflow is via `embark-collect` if I want to keep search results around for longer.

**Comment by linkenneth** [comment]
Thank you @minad! The experience is amazing and I'll definitely be putting this feature to good use.
