### ISSUE TITLE
find-file selects first candidate when on tramp home dir

### ISSUE THREAD

**Issue by billop** [minad/vertico#193]
So I've looked at these issues: https://github.com/minad/vertico/issues/192 https://github.com/minad/vertico/issues/156

And it looks like `find-file` completion should initially select the prompt if "the prompt shows a complete and valid file path". However, when connecting to a remote host, this leads to a path such as: `/ssh:user@hostname:~/` which I guess is not considered "complete and valid file path" for some reason?

Personally when it comes to `find-file` I always want the prompt to be initially selected to take advantage of `vertico-directory-tidy` at all times. Which makes me wonder why there's the conditional of if "the prompt shows a complete and valid file path". When would that not be the case? Doesn't `find-file` always have the current directory as the prompt which means it's always complete and valid?

**Comment by minad** [comment]
> https://github.com/minad/vertico/issues/156And it looks like find-file completion should initially select the prompt if "the prompt shows a complete and valid file path". However, when connecting to a remote host, this leads to a path such as: /ssh:user@hostname:~/ which I guess is not considered "complete and valid file path" for some reason?

This seems indeed to be the case. I assume the problem is the same as in #174. The file completion table reports a wrong completion boundary. See the bug I've reported https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53053. Maybe it is not exactly this issue but it is at least related. The tramp completion table does not compute correct completion boundaries.

> Personally when it comes to find-file I always want the prompt to be initially selected to take advantage of vertico-directory-tidy at all times. 

`vertico-directory-tidy` has nothing to do with if the prompt is selected or not. It will always cleanup the prompt if registered as hook.

> Which makes me wonder why there's the conditional of if "the prompt shows a complete and valid file path". When would that not be the case? Doesn't find-file always have the current directory as the prompt which means it's always complete and valid?

For example if you enter some part of a file name, then the substring is not a valid file name. In this case Vertico selects the topmost file and not the prompt such that you can navigate quickly to this file. Only if the prompt is a valid path itself it is selected such that you can easily open directories. If you want to change the logic of `vertico--update-candidates` you can use an advice. See

https://github.com/minad/vertico/blob/1bd5438da9c661e2df5e9516f36d9cbc6d100a34/vertico.el#L440-L453

**Comment by minad** [comment]
In case you want to report the bug upstream:

~~~ elisp
(completion-boundaries "/sudo::~/" #'read-file-name-internal nil "") ;; (8 . 0)
(completion-boundaries "/sudo::/" #'read-file-name-internal nil "") ;; (8 . 0)
~~~

The return value is in both case `(8 . 0)` which is obviously incorrect.

**Comment by billop** [comment]
Oh the tidy behavior on my end is because I have `/` enter directory if the selection is a directory.

So rn I have to either change how vertico works or wait for the upstream fix? I was hoping there would be an easier general way to not auto-select candidates when nothing has been typed.

**Comment by minad** [comment]
> I was hoping there would be an easier general way to not auto-select candidates when nothing has been typed.

You can use an advice:

~~~ elisp
(defun vertico--reset-index (&rest _)
  (setq vertico--index -1))
(advice-add #'vertico--update-candidates :after #'vertico--reset-index)
~~~
