### ISSUE TITLE
How to disable vertico only for `tmm-menubar`

### ISSUE THREAD

**Issue by etern** [minad/vertico#201]
The README `tmm-menubar` part shows how to disable tmm completion buffer, but I think the default tmm Complation buffer is better, how can I disable vertico only for `tmm-menubar` ?

**Comment by minad** [comment]
Vertico doesn't offer that feature currently ootb. But writing a vertico-disabled-mode is easy, see https://github.com/minad/vertico/issues/168#issuecomment-1006049216.

Why do you consider the `*Completions*` buffer as better in this particular case? As alternative you could check out vertico-buffer+vertico-grid enabled via vertico-multiform only for tmm. This should give you a similar result.

You may also want to give Mct a try, which combines the default Completions buffer with Vertico-style navigation elegantly.

**Comment by H-Tung** [comment]
Sorry to post in such an old issue.  However I couldn't get `vertico-multiform-grid` or `vertico-grid-mode` work with `tmm-menubar`. Here is a screenshot showing the configuration I used to see if something else was causing the problem.
```emacs-lisp
;;; init.el -*- lexical-binding: t -*-

  (use-package vertico
      :hook (after-init . vertico-mode)
            (vertico-mode . vertico-multiform-mode)
      :custom (vertico-multiform-commands '((tmm-menubar grid))))

```
![图片](https://github.com/user-attachments/assets/3cdf2d73-83dc-4fde-a274-771c10d8abdc)

P.S. I installed `GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05` via scoop on Windows 10.

**Comment by mmarshall540** [comment]
> Why do you consider the `*Completions*` buffer as better in this particular case? As alternative you could check out vertico-buffer+vertico-grid enabled via vertico-multiform only for tmm. This should give you a similar result.

Can't speak for OP from 3 years ago, but before committing to Vertico I had `tmm-menubar` set up with `(setopt completions-format 'one-column)`. This provided a nice vertical list of all menu entries. After switching to Vertico, I noticed that for most menus I had to scroll down to see all of the entries.

This was because Vertico limits visible candidates to the value of `vertico-count`, which is only 10 by default. But some menus have more than 25 entries. So I tried changing the value to 30. But that also makes Vertico cover more than half of the window just to complete a variable, function or other symbol.

So I did this...

```lisp
(setopt vertico-multiform-mode t)

;; Show all menu entries with Vertico.
(add-to-list 'vertico-multiform-commands 
             '(tmm-shortcut (vertico-count . 30)))
```

Now I get full menu display for the `tmm-menubar` but a reasonable maximum height when using Vertico with other commands. 🥳

**Comment by yocoldle** [comment]
As a user who simply wants to use the native tmm interface, my crude approach is to wrap it with an advice. Although this will globally affect vertico, tmm generally doesn't survive for long, so the impact is within an acceptable range.

It just works.

```elisp
(advice-add 'tmm-menubar :around
            (lambda (fn &rest args)
              (vertico-mode -1)
              (unwind-protect (apply fn args)
                (vertico-mode 1))))
```
