### ISSUE TITLE
Document how to generate vertico.texi

### ISSUE THREAD

**Issue by DamienCassou** [minad/vertico#204]
I installed vertico with a git submodule through [borg](https://github.com/emacscollective/borg/). Vertico comes with a README.org which can be compiled into a vertico.texi to later get an Info manual.

I think it would make sense to document how to programmatically generate a texi file from the README.

**Comment by minad** [comment]
Sorry, documenting basic things like this is not the business of Vertico. People can read the Org and Info manuals. Furthermore as I mentioned in #203, I would expect ELPA/MELPA to generate manuals such that they are automatically available to users via the usual package installation, which should make the Info manuals a non-issue for most users. Currently this seems not to be the case, but this should be fixed in ELPA/MELPA. Users who install packages via other means, e.g., straight (or borg which seems to target experts), can look up the documentation of their package manager, since this is the place where such documentation belongs.

**Comment by DamienCassou** [comment]
Thank you for you answer. For those who care:

```ini
[submodule "vertico"]
	path = lib/vertico
	url = git@github.com:minad/vertico.git
	branch = main
	build-step = borg-update-autoloads
	build-step = borg-compile
	build-step = (require 'ox-texinfo)
	build-step = "(save-excursion (find-file \"README.org\") (org-export-to-file 'texinfo (org-export-output-file-name \".texi\")))"
	build-step = borg-makeinfo
```

**Comment by minad** [comment]
I wonder - why is there no `borg-orgtotexi` predefined build step?

**Comment by DamienCassou** [comment]
Discussion continued in https://github.com/emacscollective/borg/issues/121.
