### ISSUE TITLE
org-refile targets not listed properly

### ISSUE THREAD

**Issue by titaniumbones** [minad/vertico#206]

**Comment by titaniumbones** [comment]
argh, I knew I'd seen this somewhere before, but forgot to look in the vertico readme.  Yes, this fixes the issue, sorry for the noise.  

I know Ihor is working on a new implementation of org-refile. Would you like me to try to raise this on the org ML? I am a bit unclear on how completion boundaries are defined in the table, though.

**Comment by minad** [comment]
It would be great if `org-refile` or the org outline path completion is properly rewritten with completion boundaries. Then it would work just as well as the normal file name completion of `find-file`. See `completion-file-name-table` for reference:

~~~ elisp
(completing-read "File: " #'completion-file-name-table)
~~~

I'd appreciate if you raise the issue on the org-mode mailing list. We can also ping @yantar92 directly. Ihor, I hope you don't mind the ping!

**Comment by titaniumbones** [comment]
I guess the relevant code is in `org-refile-get-targets` in org-refile.el.  It is a bit hard for me to follow when I'm stealing furtive glances at it instead of doing my actual job. @yantar92 Hopefully the comparison between the two ocmpletion functions makes sense to you!

**Comment by yantar92** [comment]
Daniel Mendler ***@***.***> writes:

> It would be great if `org-refile` or the org outline path completion is properly rewritten with completion boundaries. Then it would work just as well as the normal file name completion of `find-file`. See `completion-file-name-table` for reference:
>
> ~~~ elisp
> (completing-read "File: " #'completion-file-name-table)
> ~~~
>
> I'd appreciate if you raise the issue on the org-mode mailing list. We can also ping @yantar92 directly. Ihor, I hope you don't mind the ping!

I support changing Org mode's completion to make it more integrated with
Emacs. There have been many complaints about hard-coded behaviour of the
existing Org mode interactive dialogues and completion functions. For
example, see
***@***.***

Unfortunately, these changes are not always trivial. My past experience
with org-refile completion code is not very positive - there are some
undocumented conventions there, which make the code fragile to changes.
Of course, patches are welcome. (This issue is not the highest in my todo
list for Org - I am personally using custom org-ql-based refile function)

In any case, raising the issue in org-mode mailing list would be
welcome. Maybe someone can be inspired by it and propose actual patch.

Best,
Ihor

**Comment by yantar92** [comment]
> ***@***.***
https://orgmode.org/list/8c364693bf6856e60cdd3e8b63ab0c9284d16733.camel@heagren.com

**Comment by minad** [comment]
@titaniumbones Can you please raise the issue again on the mailing list? I think one should take small steps. Transients for popup dialogs are an orthogonal issue to improving some individual completion functions. (I am in favor of Transients of course in contrast to the current Org dialogs, which are just not as polished. I think we can get a more coherent UI overall with Transient.)
