### ISSUE TITLE
Problem with "RET to end" commands

### ISSUE THREAD

**Issue by astoff** [minad/vertico#208]
Commands that read a list of things with "RET to end" conventions don't work with Vertico: it's impossible to enter an empty value. I'm aware of two: `multi-occur` and `auto-insert`. I guess you have a good reason not to obey the official meaning of the `require-match` argument?

```
REQUIRE-MATCH can take the following values:
- t means that the user is not allowed to exit unless the input is (or
  completes to) an element of COLLECTION or is null.
```

**Comment by minad** [comment]
Duplicate #128, #205, #208

**Comment by astoff** [comment]
Sorry I didn't notice the antecedents :see_no_evil:

**Comment by astoff** [comment]
That said, there is a section on "problematic commands" that could mention this. Being/thinking that you are stuck in an infinite loop seems problematic enough.

**Comment by minad** [comment]
A PR is always welcome :)

To make my reasoning more explicit - there are the following two scenarios, where "" is allowed as default value, but only in the second case the default value is made explicit and Vertico preselects the empty prompt. In the first case, the first matching candidate is preselected. This is what you usually want, since the empty default is always allowed by completing-read (called the null completion)! Ideally the problematic commands would specify an explicit empty default value.

~~~ elisp
(completing-read "Prompt: " '("first" "second" "third") nil 'require-match)
(completing-read "Prompt: " '("first" "second" "third") nil 'require-match nil nil "")
~~~

**Comment by astoff** [comment]
I agree with the rationale, I just didn't know how to deal with the problematic commands.
