### ISSUE TITLE
[question] How to ignore completion when I don't want it?

### ISSUE THREAD

**Issue by AndersonTorres** [minad/vertico#211]
Hello, people! I am Anderson, an Emacs newbie for more than 10 years. I came to know Vertico from the System Crafters' videos about Emacs.

Case in point:

I have a file with the name `the-use-of-upanishads-by-arthur-schopenhauer.org`.
I want to rename it to `the-use-of-upanishads.org` using Dired `R` (`dired-do-rename`) command.

However, it fails with the message `cannot move to the same file: `/tmp/the-use-of-upanishads-by-arthur-schopenhauer.org`.
Of course it happens because the old name is still in the completion list of possibilities.

How can I instruct Emacs to ignore the completion provided by Vertico and use the input I have provided instead?

Just to make sure, I don't want something that disables it completely, because the completions are useful in other similar contexts, like rename the file to `the-use-of-upanishads-by-arthur-schopenhauer-in-his-letters.org`.

**Comment by hmelman** [comment]
I think you want to use `M-RET` instead of just `RET` this will call `vertico-exit-input`.  

Generally there's a difference between having a command select one of the candidates or the input that you type.  All the completion frameworks have a way to do this and they're bound to different keys (some use `C-j`, others `C-M-j`).  Vertico is at least consistent about it.  If you hit just `RET` it will use whatever is highlighted.  You can also use `C-p` to move the highlighted selection up to the input you typed and then use `RET` to choose that instead of a candidate.  I find this isn't obvious at first, but once you see it, it makes a lot of sense.

**Comment by AndersonTorres** [comment]
Hum, that's weird.
By some obfuscated reason the `vertico-exit-input` was bound to `C-RET`, not `M-RET`.

Nonetheless, it solved my issue for now: I need to bind `vertico-exit-input` to a suitable keystroke...
Therefore, I will close this as solved.

Thanks, @hmelman!

**Comment by hmelman** [comment]
The default binding was changed from C-RET to M-RET about a month ago.  See #196

**Comment by AndersonTorres** [comment]
Time to update my [Nixpkgs](https://github.com/NixOS/nixpkgs/pull/164822) setup, then!

**Comment by salutis** [comment]
>  You can also use `C-p` to move the highlighted selection up to the input you typed and then use `RET` to choose that instead of a candidate.

TIL! 😀
