### ISSUE TITLE
Make minibuffer-local-filename-completion-map's keys available when completing file 

### ISSUE THREAD

**Issue by daanturo** [minad/vertico#214]
Emacs's vanilla `completing-read-default` has support for that, it's should be nice for `vertico`, too.

**Comment by minad** [comment]
No, I disagree with this. Completion has the concept of completion categories. It does not make sense to also use a separate keymap for each of the categories. `minibuffer-local-filename-completion-map` is a historical remnant from before the introduction of completion categories.

Also note that Vertico cannot replicate every single detail of the default completion system. This becomes even more relevant the more default completion is augmented with additional configuration options and features which are specific to the default completion system (see for example recent changes in Emacs 29). 

One has to distinguish between the default completion system (the UI) and the completion styles API and basic completion machinery. Vertico relies on the fundamental Emacs completion machinery, but this does not necessarily mean that every feature from the default completion UI transfers to Vertico. I should probably clarify this in the README.

**Comment by minad** [comment]
I try to visualize how the systems approximately build upon each other:

~~~ 
   Mct
    |
default UI  Vertico        Selectrum  Ivy   Helm
    |          |           |   .       |     |
default completion machinery   .       |     |
(completion styles etc)        .       |     |
         |                     .       |     |
------ minibuffer APIs --------------------------
~~~

Unfortunately the problem is that the separation between the default completion UI and the more basic completion machinery is not that clear. Most of the code is maintained in minibuffer.el and some part of the default UI are maintained in simple.el. It would be much nicer if the default completion UI would be separated from the lower level completion code. But in any case the keymaps used by the default completion UI clearly belong to the UI and not to the level below it.

**Comment by minad** [comment]
See also some prior discussion about this in #4.
