### ISSUE TITLE
Vertico conflicts with  pixel-scroll-precision-mode

### ISSUE THREAD

**Issue by Eason0210** [minad/vertico#216]
In Emacs 29, the new feature [pixel-scroll-precision-mode](https://github.com/emacs-mirror/emacs/blob/45621c0b79b9c480501c77666a54562069653338/lisp/pixel-scroll.el#L817) was introduced, which enables pixel scrolling with touchPad or mouse. But when `vertico-mode` is enabled, `pixel-scroll-precision-mode` doesn't work properly with inactive buffers.

Steps to reproduce:

1. Enable Emacs with `emacs -q`
2. Install `vertico` , enable `vertico-mode` and `pixel-scroll-precision-mode`

```emacs-lisp
(package-refresh-contents)
(package-install 'vertico)
(pixel-scroll-precision-mode t)
(vertico-mode 1)
```
3. Create 2 buffers arbitrarily, and scroll the inactive buffer through the touchPad

I've reported the issue to the maintainer (Po Lu) of `pixel-scroll-precision-mode`, but he couldn't reproduce the issue.

Do you have any suggestions?

**Comment by minad** [comment]
> But when vertico-mode is enabled, pixel-scroll-precision-mode doesn't work properly with inactive buffers.

Thanks for the report! Can you please give me more details? "does not work properly" does not describe the issue sufficiently. If Po Lu cannot reproduce the issue I can probably reproduce it neither. Note that I cannot support Emacs 29 yet. I will look into this in maybe half a year when I switch to the master branch myself. Currently I use Emacs 28 since there is way too much churn on the master branch (basic refactorings of pgtk etc). However I am eager to try Emacs 29 in particular because of the many performance improvements which are added there! :smile:

**Comment by minad** [comment]
But from how I understood you, the issue seems to be present even if no minibuffer is open? An influence of Vertico seems very unlikely, since Vertico doesn't interfere with any of the scrolling or other basic display infrastructure. See here for the advices added by Vertico:

 https://github.com/minad/vertico/blob/c88643ad246963c6288f2b7f88e98b671be165f6/vertico.el#L763-L771

If Vertico is inactive (no minibuffer), there is no Vertico code running, no hooks, no active advices, no nothing. I close this since I doubt that Vertico has anything to do with this and I am hopeful that the issue will disappear anyway in the future when more Emacs 29 bugs are fixed. In any case I will revisit this when I switch to Emacs 29 myself.

**Comment by minad** [comment]
Okay from your video it does not look as if Vertico is causing this. This seems like a bug of `pixel-scroll-precision-mode`. Or maybe the bug was caused by some other malfunction, since in the start of your video I briefly saw the command "vim". Something is wrong! ;)

**Comment by minad** [comment]
I know, I was just joking. I find it funny how Emacs users use Vim to "bootstrap" Emacs. ;)

**Comment by Eason0210** [comment]
Hi @minad

Just for your information.

 Emacs 29.0.50 have been fixed this issue after this commit: https://github.com/emacs-mirror/emacs/commit/fd8eaa72a611d050e1fe9c38c466c7812c7795dd

Now, vertcico works well with `pixel-scroll-precision-mode`

The maintainer said that it's cause by `vertico `uses `window-resize` to resize the minibuffer window.

**Comment by minad** [comment]
@Eason0210 Thanks, that's good!

> The maintainer said that it's cause by vertico uses window-resize to resize the minibuffer window.

Yes, this has probably exposed the bug in pixel-scroll-precision-mode. But I don't think there is anything wrong with resizing the minibuffer? Vertico notably uses *manual resize* via `window-resize` but we could also rely on the auto resizing feature of the minibuffer if you set `resize-mini-windows`. Auto resizing didn't work too well in my tests (in particular on older Emacsen). But I think this has gotten better in 28 and 29.
