### ISSUE TITLE
Optional 1-based indexing

### ISSUE THREAD

**Issue by noctuid** [minad/vertico#218]
I've used the home row for numbered actions for a long time. For example, altgr+a is 1, win+a selects desktop 1, M-a selects the first completion candidate, etc. The default indexing doesn't match what I'm used to, so it would be nice if there was an option to show 1-based indexing instead like selectrum. (I also think of the prompt as index 0).

**Comment by minad** [comment]
You mean the indexing of vertico-indexed-mode?

**Comment by noctuid** [comment]
Yes, specifically the displayed index. I don't care about the underlying vertico--index and am not actually using prefix arguments for selection but dedicated commands (though it would make sense to have the prefix arguments match for consistency).

Alternatively, if there was some way to map the indices to a letters instead (e.g. show `a` for index 0) kind of like `company-quick-access-keys` with `company-show-quick-access` non-nil, that would be just as good for my use case.  This would be simple to implement myself but might be nice to have builtin.

Speaking of company, I'd like the same functionality in corfu but will make a separate issue there if you're open to it.

**Comment by minad** [comment]
We can add all these things, but it is quite different from the current implementation of vertico-indexed and corfu-indexed. There are these different aspects:

- Use an index offset to map the prefix integer to a candidate (currently 0, but we could make it configurable and allow 1)
- Display numbers depending on the index offset
- Lookup letters in a `vertico-indexed-keys` string and display them instead of the index
- Bind keys, e.g, `s-<letter>` and map to indices

We would need four configuration options to handle all different combinations:

- `vertico-indexed-offset` can be 0, 1, ...
- `vertico-indexed-keys` a string of letters
- `vertico-indexed-display` which can be `key` or `index`
- `vertico-indexed-modifier` which can be nil or `super`, `hyper`, etc.

Alternatively one creates entirely separate extensions `vertico-indexed` which stays as is (+ maybe `vertico-indexed-offset`) and `vertico-keys` with two options `vertico-keys-string` and `vertico-keys-modifier`. I am not sure. `vertico-indexed` is quite simple currently so maybe it makes sense to keep it that way.

**Comment by noctuid** [comment]
For my personal use case, I only want `vertico-indexed-offset` or `vertico-indexed-keys` (I don't need both). I don't need automatic keybindings either, though that would make sense for `vertico-indexed-keys`. Even a `vertico-indices` to just relabel the indices would be good enough for me.

**Comment by minad** [comment]
> Even a vertico-indices to just relabel the indices would be good enough for me.

Sure but that's only your personal use case. The end result should also be useful for a wider user base so it is not sufficient to just provide a different display.

**Comment by minad** [comment]
I think it makes sense to do these two things:

- Add vertico-indexed-offset to the existing vertico-indexed for more flexibility
- Add a separate vertico-keys extension which binds keys

There will be a little bit of code duplication of the display code but this is only a ten line function. Besides that the functionality will be different. The same should be done for Corfu to keep the two packages in sync.

**Comment by minad** [comment]
I close this issue due to inactivity. Feel free to contribute a PR which adds this feature.

**Comment by minad** [comment]
Fixed partially by #266.
