### ISSUE TITLE
Current path shown in curly braces when I start a new file path with ~

### ISSUE THREAD

**Issue by samcramer** [minad/vertico#221]
I apologize if this is the not the correct forum for this or if this is in fact the intended behavior.

As of late, when I have tried to select a new file to edit and give a new starting point for the file path in the minibuffer, I see something like this:

![vertico-weird-behavior](https://user-images.githubusercontent.com/6877655/164068778-b8be4254-7033-44d6-a2de-edfa8b61c4b8.png)

I want to have the selection start at `~` in this case. Do I have something misconfigured?  Is this a bug?

**Comment by minad** [comment]
This doesn't look correct. Maybe you have *both* `vertico-mode` and `icomplete-mode` activated or you misconfigured `vertico-multiform-mode`? Please check that you don't have different completion UIs active at the same time. In order to use `vertico-mode`, you should first deactivate all the different other completion UI modes in case you have one of them installed, `selectrum-mode`, `icomplete-mode`, `ivy-mode`, `helm-mode`, `ido-mode`, `mct-mode`, ... Maybe the reason could also be a misconfiguration 

I suggest to narrow down the issue in your configuration by enabling parts of it step by step. If the issue persists you can always start from `emacs -Q` and activate only a minimal set of packages and modes. I hope this is helpful!

**Comment by samcramer** [comment]
Thanks @minad.  I will try what you suggest.  Thanks for writing this awesome package, BTW!
