### ISSUE TITLE
`read-minibuffer-restore-windows` = nil leaves minibuffer/window behind

### ISSUE THREAD

**Issue by jdtsmith** [minad/vertico#222]
Just upgraded to Emacs 28.1 and noticed that the new, very useful setting `read-minibuffer-restore-windows` = nil does not play well with vertico, e.g. in consult-line, leaving the mini-buffer behind after a line is selected with Return:

```elisp
(setq read-minibuffer-restore-windows nil)
(package-initialize)
(require 'consult)
(require 'vertico)
(vertico-mode)
(consult-line)
```

This also acts strangely when using the `buffer` vertico-multiform flavor, in which case the special buffer is left behind after line selection.

**Comment by minad** [comment]
I don't think that this disruptive setting should be set globally currently, only per completion command locally. There are just too many scenarios where this setting will break everything since usually completion systems are written with the window restoration in mind. It will certainly affect Vertico and Consult preview. If you want you can investigate where we would need changes and propose PRs. For now I consider this setting as wontfix.

**Comment by jdtsmith** [comment]
OK thanks for your thoughts.  The usual scenario where I want to leave the window configuration alone is when, from minibuffer completion, I use embark to visit another buffer (like *Help*) in a window, or I navigate away from the minibuffer and change the windows around.  That seems to happen much more with the power of embark.

Do you think that main issue is that it's hard to decide in advance which windows are "temporary", and which are considered a user choice to have visited?  I'd suggest that minibuffer mirroring windows opened could safely be considered alway temporary, and actively cleaned up .  After all that's what embark snapshot is for.  I was surprised by the simple example I showed above that the _minibuffer itself_  sticks around when `read-minibuffer-restore-windows` is nil.  That seems like an odd choice (or maybe I'm confused about that). 

BTW, here's what the widely circulated "What's new in Emacs 28.1" Mastering Emacs article has to say about this new setting:

> If you regularly activate your minibuffer only to C-x o out of it and do something else, you may find that when the time comes to finish the minibuffer command that you’ve changed your window layout. The minibuffer remembers the window state of when you activated it, and it snaps back to that when you exit.
It’s very annoying, so I’m definitely enabling this!

So I bet plenty of people will try doing this...

**Comment by minad** [comment]
In the long term we will probably support this setting and I am hopeful that it improves the UI experience since it makes the minibuffer more well-behaved. Maybe in the long term it even makes sense as a better global default. However as of now I do not agree with the recommendation to turn this on and expecting things to just work as is. I expect many of the completion packages to be broken due to this change. This feature needs more preliminary investigations: Testing Vertico and all its extensions, documenting what breaks, what works better, testing many builtin completion commands to get a clear picture, testing all the Consult commands with preview, ... Maybe it is possible to turn this setting on for some commands only locally via `vertico-multiform-mode`? Maybe we can take special advantage of this setting in Embark (per command or globally)? Currently I don't have a clear picture at all about this and too many open questions. One should probably use Emacs for a week with this setting to figure out most of the issues. If you are truly interested in this feature, documenting problems would go a long way. Then we can figure out which kind of changes are needed. I think it is important to first get a better and more complete picture before thinking about fixes since otherwise we may not end up with a sufficiently general solution. It could also be that I am too pessimistic about this and that most things indeed will just continue to work well. I am at least somewhat hopeful that the recent protocol improvements to Consult preview (the `:state` function) circumvent some potential issues of the missing window restoration.

**Comment by minad** [comment]
@jdtsmith In the meantime, did you try this setting again? I just enabled it after I got reminded by it in the [Emacs tips and tricks](https://old.reddit.com/r/emacs/comments/18hc301/weekly_tips_tricks_c_thread/kdobd72/). So far the only thing which breaks is `consult-buffer-other-window`, which leaves around the other window even when exiting the completion session with C-g. Besides that, the setting is not bad, in particular with Embark where windows stay around when acting. I'd like to collect of features which do not work well with that setting and maybe fix them one by one.

**Comment by jdtsmith** [comment]
I haven't reenabled it, but I do wish for it when I go on a long meandering walk around various buffers during a recursive edit.   Will try again.

**Comment by minad** [comment]
For now I've enabled this setting by default and will run for it for a while as long as I don't observe any heavy breakage. It certainly makes recursive minibuffers more comfortable. In case you also try it, please let me know your findings.

**Comment by jdtsmith** [comment]
Excellent! Will give it another try and report any issues.
