### ISSUE TITLE
Support two levels of details for file completion

### ISSUE THREAD

**Issue by yalfg** [minad/vertico#245]
This is a suggestion to support two levels of details for file completion:
1.  A default level, showing and completing based on "interesting" files only. Dot files are not shown, and `completion-ignored-extensions` is used;
2. A detailed level, with no filtering. Dot files are shown and used for completion, and `completion-ignored-extensions` is ignored.

This is to be closer to the default Emacs behavior. By default it filters for completion and shows nothing, so the dot files are not in the way, except if one explicitly use a dot (well suited for prefix completion, but not to something like `orderless`). If one tab with no candidate, then the completion buffer shows it all and `completion-ignored-extensions` is ignored. For `vertico` it's better IMHO to switch between modes explicitly with a shortcut, as the implicit switch with no candidate wouldn't work so well with something like `orderless` (type a bit too much and sees dot files? Too surprising).

Today `vertico` has a "middle of the road" behavior, with a unique level of details showing dot files and always filtering based on `completion-ignored-extensions`. I found showing dot files surprising as the Unix convention is to hide them by default, and it's no so user friendly IMHO: when using `vertico` for the first time on my home directory I saw only dot files I didn't care about, with the interesting stuff pushed out to a second screen. Maybe not a bit deal for people using `orderless`, but I prefer the old fashion tab prefix completion for files (I use `orderless` for "big context" completions).

Also, showing dot files but filtering by `completion-ignored-extensions` leads to the "where's .git?" issue IMHO. This behavior is understandable from the implementation, but as a lot of new users I guess I didn't know about the implementation at first ;)

I believe having the above two levels would behave more as expected by new users, particularly the old emacsers stuck to tab completion for `find-file` like me.

Here's what I did to prototype this. I'm far from an experienced elisper so I've no doubt this can be improved. But it works for me, and allowed noticing a few things (discussed below):

```elisp
(defvar my/vertico-files-details nil
  "Filter dot files and using `completion-ignored-extensions', or not.")

;; All the filtering could be done here if preferred
(defun my/vertico-file-filter-advice (func files)
  "Filter FILES with FUNC, or don't filter."
  (let ((myfiles (seq-remove
                  (lambda (x) (or (string= x "./")
                                  (string= x "../"))) files)))
    (if my/vertico-files-details
        ;; Skip vertico filtering
        myfiles
      ;; Regular vertico filtering
      (funcall func myfiles))))
(advice-add 'vertico--filter-files :around #'my/vertico-file-filter-advice)

(defun my/vertico-refresh ()
  "Update vertico display after some global state change."
  (let ((pt (max 0 (- (point) (minibuffer-prompt-end))))
        (content (minibuffer-contents)))
    (vertico--update-candidates pt content)))

(defun my/minibuffer-complete ()
  "Replacement for `minibuffer-complete' with support for details level."
  (interactive)
  ;; Use elisp dynamic scoping to shadow `completion-ignored-extensions'
  ;; and set it to nil (so no filtering) while completing, if we want
  ;; details
  (let ((completion-ignored-extensions
         (if my/vertico-files-details
             nil
           completion-ignored-extensions)))
    (minibuffer-complete)))
(define-key vertico-map (kbd "<tab>") #'my/minibuffer-complete)

(defun my/vertico-files-details-toggle ()
  "Toggle between filtered and full files views"
  (interactive)
  (setq my/vertico-files-details (not my/vertico-files-details))
  (my/vertico-refresh))
(define-key vertico-map (kbd "s-d") #'my/vertico-files-details-toggle)

;; Used for files with `vertico-multiform`. Not only sort, but also filter if needed
(defun my/sort-files (files)
  "Sort FILES into norm dir, norm files, dot dir, dot files."
  (let* ((files (vertico-sort-alpha files))
         (dlist (seq-filter (lambda (x) (string-suffix-p "/" x)) files))
         (flist (seq-remove (lambda (x) (string-suffix-p "/" x)) files))
         (nd (seq-remove (lambda (x) (string-prefix-p "." x)) dlist))
         (dd (seq-filter (lambda (x) (string-prefix-p "." x)) dlist))
         (nf (seq-remove (lambda (x) (string-prefix-p "." x)) flist))
         (df (seq-filter (lambda (x) (string-prefix-p "." x)) flist)))
    (if my/vertico-files-details
        (nconc nd nf dd df)
      (nconc nd nf))))
```

I tried at first to advice `vertico--filter-files` as suggested in issue #229: it works well for the vertico display, but as I'm using the old prefix completion the completion still filtered by extension. So locally setting the extension list to nil is more robust.

Would you consider adding a `vertico-refresh` as part of the public API? I think it's helpful to make customization easier: a user can change whatever state and use this to update the vertico display, without knowing or depending on the internals. What I did above seems to work for me, but may not be enough for the general case.

I've over-reached a bit for the sorting: vertico provides a way to customize it, and I use this also for filtering. This allows, even in detailed mode, pushing the dot files at the end. With the current vertico implementation this works, but is this dependable? Could it be part of vertico public API?

Thanks for your time and all the good stuff!

**Comment by minad** [comment]
For now I am hesitant to change anything with respect to filtering and file handling. The default completion system also doesn't hide files (as you proposed as option 1). It only ignores the `completion-ignored-extensions` when completing with TAB. We are somehow doing the same here in Vertico and hide the candidates directly in the minibuffer. In Vertico TAB completion usually works differently, since it uses the currently selected candidate when tabbing.

As you figured out, you can disable filtering by setting `completion-ignored-extensions` to nil to disable filtering. You can also overwrite the filter function according to your liking (or override the sort function for that). But then TAB completion will still include all the files.

~~~ elisp
;; Customize filtering, TAB completion won't be affected!
(defvar vertico-filter-function nil)
(setq completion-ignored-extensions nil)
(advice-add #'vertico--sort-function :filter-return #'vertico-filter-function-compose)
(defun vertico-filter-function-compose (sort)
  (lambda (x) (funcall (or sort #'identity) (funcall (or vertico-filter-function #'identity) x))))
~~~

Another option is to adjust the `minibuffer-completion-predicate` (override or compose). This is probably the best option since it affects both the display and tabbing. You can toggle these variables dynamically and then refresh.

~~~ elisp
;; Do this locally in the minibuffer
(setq completion-ignored-extensions nil
      minibuffer-completion-predicate (lambda (file) ...))
~~~

For refreshing you can use `vertico--exhibit`, see https://github.com/minad/consult/blob/main/consult-vertico.el#L41-L48.

**Comment by yalfg** [comment]
Thanks for the feedback! I had tried `vertico--exhibit` and it did nothing as there was no input change, but from reading the code again I understand now that the right way is to set `vertico--input` to `t` before calling it so I'll do this.
