### ISSUE TITLE
[question]How to wrap a long line candidate to multiple lines?

### ISSUE THREAD

**Issue by K-gihu** [minad/vertico#257]
Hi everyone!

When using org-roam, I need to select from candidates which are very long, longer than my laptop screen. But I would like to see the whole line. 
Since I use vertico as my completion backend, I wonder if there is a way to wrap/truncate the candidate lines?

**Comment by minad** [comment]
You can set `truncate-lines` to nil. But note that this is not the intended use case of Vertico. Candidates should better be formatted such that they fit on a single line. I hope this helps.

~~~ elisp
(advice-add #'vertico--resize-window :after #'set-truncate)

(defun set-truncate (&rest _)
  (setq-local truncate-lines nil))
~~~

**Comment by mentalisttraceur** [comment]
One downside of this approach is that the minibuffer grows when multi-line candidates come into view, but never shrinks back.

I think the ideal UX here (at least for me) is

1. line wrapping can be off until I see one or more candidates I actually want to see unwrapped (just because a long candidate scrolls into view, doesn't mean I want to see it unwrapped), and then it can be toggled on;

2. line wrapping doesn't change the size of the minibuffer, so long entries just push other entries down out of view when wrapped.

Anyway, I agree that ideally candidates fit in one line, but

1. On a phone, "one line" can easily be ~50 characters. (I use Emacs daily, some days heavily, on my phone - and Vertico is one of the things that makes that reasonably efficient).

2. I'm not entirely sure this is always possible or practical (in the general case, at a minimum this requires an algorithm which preprocessed candidates to look at all the long ones and figures out the smallest distinct parts to show).

Having said that, so far it seems like it's always possible to set things up so that seeing the full candidate is only a few keystrokes away.
