### ISSUE TITLE
Wrap around at beginning/end of completions?

### ISSUE THREAD

**Issue by daviwil** [minad/vertico#26]
Hey @minad, Vertico has been working great for me with a more recent build of native-comp!  Everything feels really snappy and looks great with Marginalia.  One thing I got used to while using Ivy is how when you move the selection up or down at the beginning or end of the list, the selection will wrap around to the other side of the list.  

It looks like it could be easy to add a setting for this and update the logic [here](https://github.com/minad/vertico/blob/main/vertico.el#L474-L475) to respect it.  I would submit a PR but I don't think I can do a FSF copyright assignment at the moment :(

If it's something you're not interested in adding for Vertico to keep things simple, I will understand :)

**Comment by minad** [comment]
Thanks for giving it another try. Note that it may not work well with Tramp. Icomplete is also very slow with that. In contrast, Selectrum optimizes this use case specially at the cost of more complexity in the UI. You may have seen that Vertico is a really small and focused package. Besides Tramp, Vertico should work well.

Regarding cycling, I would probably be okay with adding this, since this feature can be implemented with a tiny amount of code. Corfu also supports cycling. How should this be implemented? You might have seen that Vertico allows selection of the prompt in some cases. For example the command `find-file` allows to move from the first selected item to the prompt to enter non-existing file names.

If we add cycling it should probably work like this: prompt <-> first item <-> ... <-> last item -> prompt. For some commands prompt selection is disallowed, in this case we would only cycle between the items.

**Comment by daviwil** [comment]
I don't use TRAMP very often so that isn't really an issue for me!

Yep, I'd be fine with it going through the prompt and back around just so that the logic remains simple.

**Comment by minad** [comment]
Ah and there is one more - only the `vertico-next/previous` commands will cycle for simplicity. There is also `vertico-scroll-down/up` etc. These will stay as is. Corfu has the same logic.

**Comment by daviwil** [comment]
Sounds great, thanks so much for adding this!  I just pulled the latest changes and it works perfectly!
