### ISSUE TITLE
`vertico-directory-up` does not work in some circumstances

### ISSUE THREAD

**Issue by ethan-leba** [minad/vertico#260]
## Steps to reproduce

This is not the only way to reproduce this, but here's one way:

1. `M-x find-file`
2. `M-x vertico-directory-up`
3. Expect to move back one directory, nothing happens.
5. `M-x vertico-directory-up`
6. Works as expected

## Info
I've bisected this issue to be introduced in 7ff368e, `Remove vertico-directory--completing-file-p`. In my short investigation, it appears that the `vertico--metadata` variable is not being populated properly.

**Comment by minad** [comment]
I cannot reproduce this issue. This problem occurs only if Vertico is not initialized properly. Usually directly after starting completion and as soon as you enter some input, the internal Vertico state is (re-)computed (candidates, metadata, etc). If this doesn't happen or hasn't happen yet you executed `vertico-directory-up` too early, or for some reason the initialization doesn't happen for you. I assume you also don't see the files - I mean the display doesn't update?

Now one can argue that such cases should be caught and computation should be enforced as long as the initialization hasn't happened. But this has wider implications for all the other Vertico commands. For example if you execute `vertico-next` directly after minibuffer setup, but before Vertico computed the candidates, the command has no effect. This is the same here, as long as the Vertico state hasn't been computed `vertico-directory-up` has no effect.

**Comment by minad** [comment]
I assume you use Doom Emacs? There I've recently stumbled over https://github.com/doomemacs/doomemacs/issues/6622, where Vertico takes a lot of time to initialize. This makes the problem more pronounced. Unfortunately it is not yet clear why initialization takes so much time in Doom. It seems most time is spent in the functions which check if minor modes should be enabled in the minibuffer. These functions call add-hook which takes most of the time. This shouldn't happen since the hook lists are usually very short. If not, something is seriously wrong.

**Comment by minad** [comment]
I reverted https://github.com/minad/vertico/commit/7ff368e5c0ca5d42252fc53071c8e239140ee552 for now such that vertico-directory-up works more gracefully if Vertico didn't compute the candidates yet. But I would still like to know why and when this issue occurs for you, since Vertico usually initializes quickly.

**Comment by minad** [comment]
I made another change regarding the initialization behavior, in this case about the handling of null completion, see https://github.com/minad/vertico/commit/a2e9b1b9b04c78e15cc2272a122e7005947d7308. When pressing RET too early (before the candidate computation finished) it was accepted even if REQUIRE-MATCH is non-nil.

**Comment by ethan-leba** [comment]
Thanks for looking into this quickly! Yes, I'm on Doom Emacs. I expect the issue that you linked is a related issue to what I'm facing -- after messing around a bit, it looks like vertico will sometimes get into a state where no candidates will be shown unless I explicitly call `vertico-insert`. Unfortunately I'm not really sure what is causing it, I don't have a consistent reproduction.

**Comment by ethan-leba** [comment]
It looks like this is actually being caused by the use of `mini-frame-mode` in my case, when I disable it vertico populates the mini buffer as expected

https://github.com/muffinmad/emacs-mini-frame
