### ISSUE TITLE
Vertico and org-cite do not work well

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [minad/vertico#261]
Steps to reproduce:

1. Set up vertico-mode
2. Create an org-mode file with an initial `#+bibliography` key that points to some bibtex file
3. Attempt to insert a citation using `C-c C-x @`
4. Vertico will offer one option, but whenever `C-j` or `RET` is pressed, it simply adds one more key `Wallquist2009:` to the citation list, never finishing.
5. More generally, this seems to be caused by the fact that vertico-mode never allows for empty input on certain fields.

Example file `example.org`
```
#+bibliography: ./example.bib
```
Example bibliography `example.bib`
```
@article{Wallquist2009,
  title = {Hybrid Quantum Devices and Quantum Engineering},
  author = {Wallquist, M. and Hammerer, K. and Rabl, P. and Lukin, M. and Zoller, P.},
  year = {2009},
  month = dec,
  journal = {Physica Scripta},
  volume = {T137},
  pages = {014001},
  publisher = {{IOP Publishing}},
  issn = {1402-4896},
  doi = {10.1088/0031-8949/2009/T137/014001},
  langid = {english}
}
```

**Comment by minad** [comment]
Try M-RET.

**Comment by juanjosegarciaripoll** [comment]
Why is this not offered as option in the C-h mode description?

**Comment by minad** [comment]
I think it doesn't appear in the mode description since the vertico-map is only installed in the minibuffer. The command M-RET is also documented in the readme.

But I think org-cite could do a little better by passing the empty string as default argument. Then Vertico would directly accept RET and the first candidate wouldn't get selected immediately.
