### ISSUE TITLE
`vertico--index`'s default value doesn't matter/how to set the index selected by default?

### ISSUE THREAD

**Issue by Atemu** [minad/vertico#272]
Vertico selects the prompt by default while I'd actually prefer it to select the first candidate. `vertico--index` decides where the cursor is and it's set to `-1` by default which makes sense as that's the prompt.

So I tried

```lisp
  (setq-default vertico--index 0)
```

but that doesn't affect vertico's behaviour. The default is set globally in Emacs but it gets overridden with `-1` when the minibuffer is opened (confirmed using `describe-variable`).

This violates the principle of least surprise IMO. What's the actual way to set the default index? The only other solution I was able to find was to use an advice after `vertico--update-candidates` but that seems hacky.

**Comment by minad** [comment]
The prompt selection logic is more complicated. The prompt is only selected if the prompt is a valid candidate. This allows you to open directories in find-file. The prompt is not selected otherwise, if the REQUIRE-MATCH argument of completing-read is non-nil. See:

https://github.com/minad/vertico/blob/64cdacd49c60bb610a1dae74cbcb9581534a8ebd/vertico.el#L444-L450

If you want to override this you can use an :after advice of vertico--update-candidates and set vertico--index to 0 if vertico--total > 0. You can experiment with this setting and check if it fits you better. But I suggest you try Vertico with the current behavior, which has been designed to handle most scenarios well. Please describe a few commands where the current behavior does not work well. If necessary we could introduce an option but I didn't have issues with the current behavior so far.

**Comment by Atemu** [comment]
Thanks for the pointer.

I've looked into it further and the actual problem is that `vertico--index` gets overridden unconditionally in the setq before this block even if `index` isn't being passed.  
In fact, all of those properties will always be overridden with at least nil (or an actually explicitly passed properties) no matter what their value was before because `(get)` returns nil when a property doesn't exist too.

Is that intended?

If I pull index out into something like

```lisp
       (when index (setq vertico--index index))
```

It keeps the default I set previously as expected.

> If you want to override this you can use an `:after` advice of `vertico--update-candidates`

Yeah, that's what I meant. It feels hacky and doesn't compose. If I've got another advice that sets the index position based on other logic and this one comes after it, the former advice won't ever have an effect because this one sets the index unconditionally.

Respecting the default value is much simpler for my use-case and, as I said, follows the principle of least surprise.

> I suggest you try Vertico with the current behavior, which has been designed to handle most scenarios well. Please describe a few commands where the current behavior does not work well. If necessary we could introduce an option but I didn't have issues with the current behavior so far.

My main issue with the default behaviour is that if I enter a directory, I want to do something with one of its files in 95% of cases.  
In the rare case where I want to do something with the directory itself, I would just select the directory rather than enter it or I could simply go up to the prompt.

Having the first entry preselected means fewer button presses and simplifies some scenarios like deeply nested directory structures with only one child on each level.

It's also simply what I'm used to.

**Comment by minad** [comment]
I will only give a brief non-technical answer - it seems you tried to switch to Vertico just recently. I suggest you try it a bit longer as is, a month or two, before attempting to change its design. Some thought went into it. Maybe you could get accustomed to how it works.

Some of the points you make are reasonable and worth some consideration. But to be clear - it is not a goal to replicate Ivy, Helm or some other UI precisely. There is nothing wrong with continuing what you use if you like its exact design.

> Having the first entry preselected means fewer button presses and simplifies some scenarios like deeply nested directory structures with only one child on each level.

This should already work. Pressing TAB even if there is only a single candidate should insert it.

**Comment by Atemu** [comment]
> I suggest you try it a bit longer as is, a month or two, before attempting to change its design. Some thought went into it. Maybe you could get accustomed to how it works.

It's in my nature to tweak my environment to my needs and preferences. Pretty much none of my software is used in exactly the way it was designed to (not even close in many cases). And that's fine; everyone has different opinion on how things should work which is why I greatly appreciate software that lets the user express their preferences.  
It's part of software freedom for me.

This issue is all about letting me express my preference to your software in a better way.

> it is not a goal to replicate Ivy, Helm or some other UI precisely.

I don't want to replicate Ivy or Helm precisely. I do want to take certain aspects they do well and transfer those over however.  
Preselecting the first completion is one of those aspects I like about them while the minimalistic approach and clean extendability are properties I like about your "framework" (it's more than that, finding a single word to describe it is hard).

> There is nothing wrong with continuing what you use if you like its exact design.

That's the thing, I don't like their exact designs. I like some or even many aspects of their design but certainly not all of them. Your design fits my needs much better overall and in certain key aspects but it does need a few tweaks here and there for me to enjoy it fully.

For example, Ivy treats paths as a complex object that you must modify through special ivy functions.  
Meanwhile in vertico, the path is just a simple string in a minibuffer prompt that I can edit with plain old emacs string manipulation functions/shortcuts *and* I get some useful path-specific functions on top like for example directory-up.

> This should already work. Pressing TAB even if there is only a single candidate should insert it.

Indeed and that's a great design choice (showing . and .. on empty dirs only is too; your software is full of them) but I prefer to explicitly be notified of the active selection before executing on it. I don't like implicit selections all that much.  
It's just a mental thing and, of course, a preference.

Even the best design in the world can't please everyone's personal preferences.

**Comment by minad** [comment]
I understand your general sentiment, but I don't see an argument strong enough to justify the addition of an option.

I believe that adding too many options with only minimal benefits or minimal difference in behavior is not a great idea, since this will lead to a combinatorial explosion and will make the system very hard for new users. Obviously that's also only a preference of mine. I am also critical of upstream decisions to add more and more options instead of figuring out reasonable defaults. That's not always possible of course, but one could try harder in some cases.

Fortunately our conflict in preferences can be easily resolved, since you can just use an advice. I agree with you that advices can have problematic effects, but in this case that's mostly a hypothetical argument.
