### ISSUE TITLE
When a minibuffer entry expects empty input

### ISSUE THREAD

**Issue by rnkn** [minad/vertico#28]
There are a few circumstance where the minibuffer provides a list of completion candidates but also expects empty input to end input.

An example of this calling `auto-insert` in an Emacs Lisp buffer, which will ask for package keywords, and will only proceed to the next skeleton insertion when minibuffer receives empty input. In this circumstance there is no way to proceed through the `auto-insert` skeleton and the user needs to call `C-g` to abort the process.

I'm not sure if there is an easy solution to this..?

**Comment by minad** [comment]
In any case you can exit with the empty input by calling `vertico-exit-input` bound to `C-return`, since `completing-read` must allow the "null completion" according to its documentation. You can test the Vertico behavior for the following default values if require-match is non-nil:

~~~ elisp
(completing-read "Prompt: " '("first" "second" "third") nil 'require-match)
(completing-read "Prompt: " '("first" "second" "third") nil 'require-match nil nil "")
(completing-read "Prompt: " '("first" "second" "third") nil 'require-match nil nil "default")
~~~

I hope this answers your question! Please let me know if you need further clarification.

**Comment by rnkn** [comment]
Thanks!
