### ISSUE TITLE
Feature request: Separator for candidates that occupy multiple lines

### ISSUE THREAD

**Issue by rdrg109** [minad/vertico#285]
- [The context](#org50131cc)
- [The request](#org6dd4335)
- [Additional information](#orgef5fa91)

<a id="org50131cc"></a>

# The context

In `helm.el`, it is possible to set and customize the separator between multiline candidates. The separator is stored in `helm-candidate-separator`, a defcustom variable. Although this separator is shown in a separated line, it can't be selected when scrolling through the candidates. See gif below.

```elisp
(helm
 :sources (helm-build-sync-source "Title"
            :candidates '("foo\nfirst string"
                          "bar\nsecond string"
                          "fizz\nthird string")
            :multiline t)
 :prompt "Select: "
 :buffer "*my helm buffer*")
```

![2022_09_25__18_19_19](https://user-images.githubusercontent.com/74389646/192170490-370a7639-fe74-4c5a-bad6-9c7d2c7b72c3.gif)

In vertico, it is possible to show multiline candidates. Evaluating the following sexp shows a candidate list as the one from the gif below.

```elisp
(completing-read
 "Select: "
 '("foo\nfirst string"
   "bar\nsecond string"
   "fizz\nthird string"))
```

![2022_09_25__18_18_33](https://user-images.githubusercontent.com/74389646/192170553-b08f4d51-1563-4524-8cd6-a86dd82c2e0c.gif)

In my configuration, I have changed the value for `vertico-multiline` (see code block below). This make newlines be displayed as newlines instead of the default value: the `⤶` character. Thus, the completion list is shown as in the gif below.

```elisp
(setq vertico-multiline (cons "\n" "…"))
```

```elisp
(completing-read
 "Select: "
 '("foo\nfirst string"
   "bar\nsecond string"
   "fizz\nthird string"))
```

![2022_09_25__18_17_10](https://user-images.githubusercontent.com/74389646/192170572-1347911a-e5c0-42fa-8449-355aab9932c8.gif)

<a id="org6dd4335"></a>

# The request

When showing candidates that occupy multiple lines, showing a separator between the candidates can ease the recognition of the boundaries of a candidate, thus making the candidate list easier to read. For this reason, I propose creating a `defcustom` variable with this purpose (the same of `helm-candidate-separator` from `helm`).

<a id="orgef5fa91"></a>

# Additional information

In `helm`, the separator `helm-candidate-separator` is only shown when `:multiline`, an argument of `helm-build-sync-source`, equals `t`. This mean that this separator is shown even when the candidates consist of a single line (see example below)

```elisp
(helm
 :sources (helm-build-sync-source "Title"
            :candidates '("foo"
                          "bar"
                          "fizz")
            :multiline t)
 :prompt "Select: "
 :buffer "*my helm buffer*")
```

![2022_09_25__18_23_20](https://user-images.githubusercontent.com/74389646/192170599-5084ceaa-a881-4493-910c-cb7a1322cf75.gif)

**Comment by minad** [comment]
Thanks for the proposal! Candidates with multiple lines have been discussed a few times before in various issues. Truly supporting multi-line candidates involves a few more changes than adjusting the `vertico-multiline` customization option.

1. Rework `vertico--resize-window` and `vertico--display-candidates` to handle multi-line candidates.
2. Rework `vertico--arrange-candidates`, which drops excess candidates to honor `vertico-count` (height of the UI).
3. Ensure that all Vertico extensions work well with multi-line candidates, in particular the display extensions, flat, grid and buffer.

I am happy to consider a PR which improves this. After that we can consider separators. I want to make sure that you don't get a wrong impression, since you are starting with a comparison with Helm - Vertico aims to be simple and minimal. It is overall a much smaller system, while Helm is currently approximately three times the size of Vertico, Consult, Embark, Marginalia and Orderless combined. I am not interested in adding too many configuration options or blowing up the code base with rarely used features. Already candidates with multiple lines are rare. The most important command which makes use of this are `consult-yank-from-kill-ring` and `yank-from-kill-ring`. Personally I am happy with the current way Vertico treats these candidates, which is the reason why I haven't worked on this yet.
