### ISSUE TITLE
M-x followed by RET too quickly can error out

### ISSUE THREAD

**Issue by jakanakaevangeli** [minad/vertico#289]
With vertico, one can press M-x followed by RET to repeat the most recently
executed extended command.

However, I sometimes press M-x RET too quickly, resulting in [Match required]
error. In this case, RET seems to interrupt vertico's candidate computation.

Perhaps, in this special case (RET with no candidates displayed yet), we could
arrange for RET to wait for candidates to be computed.

Note that this issue isn't super important to me. `M-x M-p RET` is a nice and
reliable alternative with only one keypress more. Feel free to close this
issue.

**Comment by minad** [comment]
Yes, I have been aware of this issue for a long time. Also related issues regarding the incomplete initialization have come up a few times, see https://github.com/minad/vertico/commit/a2e9b1b9b04c78e15cc2272a122e7005947d7308 and #260.

I think we should finally fix this issue by adding functionality which enforces non-interruptible initialization.

- Introduce a vertico--init function which initializes the Vertico state and ignores input if a FORCE argument is given. Some refactoring of vertico--update-candidates etc is needed.
- Alternatively add a FORCE argument to vertico--exhibit? But then we also redisplay the UI while we are only interested in the state update. However this would ensure that the display is always consistent with the state, which may be preferable? 
- Check all the Vertico commands if they need initialization, e.g., vertico-exit, vertico-insert, vertico-directory-enter. We could again get rid of vertico-directory--completing-file-p (see #260).
- Update other packages, e.g., Embark to call vertico--init instead of vertico--exhibit, if they are interested in initialized state.

What do you think? If there is interest, I would appreciate a PR very much!

**Comment by jakanakaevangeli** [comment]
> What do you think? If there is interest, I would appreciate a PR very much!

Unfortunately, I won't be able to work on this any time soon but I too
would appreciate a PR, thanks.

**Comment by minad** [comment]
> Unfortunately, I won't be able to work on this any time soon but I too
would appreciate a PR, thanks.

Okay, thanks. Maybe I can look into this in the next few days. I am the only one working on Vertico, so it won't happen otherwise. :shrug:

**Comment by minad** [comment]
@jakanakaevangeli All these initialization issues should be gone now. I refactored both Vertico and Corfu. Please let me know if you still observe issues. Embark should also be updated, see https://github.com/oantolin/embark/pull/548.

**Comment by jakanakaevangeli** [comment]
Thanks, that was quick.

I can confirm that my usecase works now.
