### ISSUE TITLE
Reverse mode and multiple frames causes displaying issues in minibuffer

### ISSUE THREAD

**Issue by mrvdb** [minad/vertico#298]
When having multiple emacs frames, enabling ```vertico-reverse-mode``` makes the minibuffer unusable.

In reverse mode, any selection list in the minibuffer starts out blank (but is functional). Once key is pressed or window resized, list shows up.

See attached video for example.

https://user-images.githubusercontent.com/73067/206735218-e743021c-b63b-4325-8e12-3071562ce665.mp4

Normal mode with multiple frames works fine

GNU Emacs 29.0.50 (build 1, powerpc64le-unknown-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)

**Comment by minad** [comment]
I gave this a quick try in my setup and I don't see any issue. Please try to reproduce the problem with emacs -Q and provide a minimal recipe.

**Comment by slotThe** [comment]
@minad I ran into this issue today while trying out `vertico-reverse-mode`. This is with Emacs 30.0.5, but I reckon (as per this issue) that earlier versions are also affected. I'm very confused by the result, so here is a reproducer:

1. Start a new server, and spawn a new frame.

   ``` console
   $ emacs -Q --daemon=vertico
   $ emacsclient -c -s vertico
   ```

2. Install `vertico`, and enable `vertico-reverse-mode`.

   ``` emacs-lisp
   (package-initialize)
   (require 'package)
   (use-package vertico
     :demand t
     :ensure t
     :config (vertico-mode))
   (require 'vertico-reverse)
   (vertico-reverse-mode)
   ```

3. Spawn another frame.

   ``` console
   $ emacsclient -c -s vertico
   ```

4. Observe that e.g. `M-x` behaves *perfectly normal* and nothing seems to be amiss.

5. Set `scroll-margin` to a non-default value (default is `0`).

   ``` emacs-lisp
   (setq scroll-margin 1)
   ```

6. Observe that the same commands (e.g., `M-x`) now take quite a while before they show their input (it's not as bad as in OPs case for me, though). The input seems to be "there", however, since the candidates do instantly update when trying to move through the list.

7. Disable `vertico-reverse-mode`

   ``` emacs-lisp
   (vertico-reverse-mode -1)
   ```

   and observe that things are back to normal again.

**Comment by minad** [comment]
Can you reproduce it without the emacsclient? I don't observe an issue with `scroll-margin=1` after `make-frame`.

**Comment by slotThe** [comment]
Yes, I can also reproduce it with `make-frame` instead of using the emacs server. Curious that you can't reproduce it :/

**Comment by minad** [comment]
Oh, for some reason I don't see it in my setup but with emacs -Q.

**Comment by minad** [comment]
Please check if https://github.com/minad/vertico/commit/adb6c6aa6dd4417a306e6168dde3e38d3be4e759 fixes the issue for you.

**Comment by slotThe** [comment]
Yup, works like a charm, thanks! 

What a surprising interaction; I do wonder what the root cause is, but I don't think I will press the issue (at least for now)

**Comment by minad** [comment]
The root cause is that scrolling in the minibuffer is specially handled or in other words broken. There exists also `redisplay-adhoc-scroll-in-resize-mini-windows`, which hits at something being wrong on the level of the display engine. :-P
