### ISSUE TITLE
support evil's ex prompt

### ISSUE THREAD

**Issue by laalsaas** [minad/vertico#308]
I want to use vertico to complete the commands I'm typing in evil's ex prompt (the prompt you get when hitting `:`). I was [told](https://emacs.stackexchange.com/questions/75072/use-vertico-completion-also-in-evils-ex-prompt?noredirect=1#comment122729_75072) that vertico needs to support completion in the `read-from-minibuffer` function.

**Comment by minad** [comment]
The answer by @dalanicolai confuses a few things. 

If you press TAB in the `evil-ex` prompt you will call `completion-at-point`. This command triggers in-buffer completion. Vertico doesn't directly support in-buffer completion, only minibuffer completion.

In order to still use Vertico as an in-buffer completion UI, you can use `consult-completion-in-region` from my Consult package. This function does nothing else than redirecting the in-buffer completion to the minibuffer. In this case, since we are already in a minibuffer, it will start a recursive minibuffer.

~~~ elisp
(setq completion-in-region-function 'consult-completion-in-region)
~~~

See https://github.com/minad/vertico#completion-at-point-and-completion-in-region for more details. As an alternative for in-buffer completion you could also try the Corfu completion UI, see then https://github.com/minad/corfu#completing-in-the-minibuffer.
