### ISSUE TITLE
newest master doesn't like vertico when M-x is called

### ISSUE THREAD

**Issue by jaor** [minad/vertico#31]
i am almost sure this is not vertico's fault, but something updated during the last two days in emacs master, but perhaps someone will know of a quick workaround.  since my latest update, trying to M-x produces the mystifying error

           Error in post-command-hook (vertico--exhibit): (error "Invalid version syntax: ‘Org 9.0’ (must start with a number)")

and vertico fails to start for completion.  other uses, like completing buffers, etc. work well.

as i said, this is a plea for help rather than a bug report, so please feel free to close :) thanks!

**Comment by minad** [comment]
Ouch, I am seeing this too. I just compiled the recent Emacs master. It seems a new bug got introduced. I am guessing it is this one: https://github.com/emacs-mirror/emacs/commit/1af91d271e077134e272055407fb8c4312a7579b. Can you please report this via `report-emacs-bug` and link it here? The bug also occurs with default completion. It is not vertico specific.

**Comment by manuel-uberti** [comment]
I experienced this as well. @minad if nobody submits a bug report before this evening (UTC+1 here), let me know and I will do it.

**Comment by jaor** [comment]
On Thu, May 13 2021, Manuel Uberti wrote:

> I experienced this as well. @minad if nobody submits a bug report
> before this evening (UTC+1 here), let me know and I will do it.

please don't wait for me... i had to switch to 27.2 for actual work
(master is failing on me on various places, including apparently the
report-bug function) and have a busy friday ahead.  thanks!

p.s. on the bright side, corfu works like a charm here (in 28 it's all
flickers) :)

**Comment by manuel-uberti** [comment]
Sure. I too have to work but I just did a hard rest to working commit before the one pointed out by @minad, and everything's fine now. :)

**Comment by jaor** [comment]
On Thu, May 13 2021, Manuel Uberti wrote:

> Sure. I too have to work but I just did a hard rest to a working
> commit before the one pointed out by @minad, and everything's fine
> now. :)

yeah, that was plan B :)

(aside: are you using corfu with 28? last time i tried there, navigating
the pop-up (corfu-next/previous) made it flicker. as i mentioned, in
27.2 is working smoothly)

**Comment by manuel-uberti** [comment]
> (aside: are you using corfu with 28? last time i tried there, navigating the pop-up (corfu-next/previous) made it flicker. as i mentioned, in 27.2 is working smoothly)

`corfu` is working fine with no flickering for me on GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.18, cairo version 1.16.0) of 2021-05-14.

**Comment by minad** [comment]
Reported here https://debbugs.gnu.org/cgi/bugreport.cgi?bug=48410

**Comment by minad** [comment]
@jaor I am not observing flicker with Corfu on 28 (current master), similar Linux system as @manuel-uberti's. If you can observably reproduce this, please report it as a regression to the Emacs bug tracker. I am not sure if there have been recent changes which affect frames on Linux or other platforms. At least there has been some long discussion on the mailing list about frame adjustments. In Corfu there was some issue with Gnome/Cinnamon/other gtk desktops (https://github.com/minad/corfu/issues/17). The workaround in the display code could lead to flicker. On these buggy desktops the flicker problem could be worse. I am not sure about the culprit, either the gtk lib itself or the wm/compositor.

**Comment by jaor** [comment]
thanks guys.  i'll take another look at the flickering thing when i'm
back to 28.  maybe the fact that i use exwm is a factor.  or maybe it
was just a transient glitch.

**Comment by minad** [comment]
At least the M-x issue seems to be fixed in Emacs master. But the fix that has been chosen shows that something is off in the Emacs development process. There is a discussion and in the end we get a suboptimal solution.

1. First there has been a discussion about not showing or indicating obsolete commands in M-x (Good idea)
2. A patch got applied which removed the obsolete commands (Problematic)
3. There was some pushback
4. A patch got applied which instead annotates the obsolete commands (Better, but why not make this an option? Either hide, annotate or show obsolete commands.)
5. There was some pushback
6. A patch gets applied which adds some version checking on the Emacs version, such that only obsolete commands are hidden which got removed without a new name (Wat?)
7. Then it is noticed that the patch does not work for third party packages and it is even broken for some packages which are part of Emacs and use an "invalid" version string
8. Instead of fixing the issue properly (for example adding an option to customize the treatment of obsolete commands), an ignore-errors is added around the problematic code

:disappointed:

**Comment by jaor** [comment]
:)

sometimes i think that emacs devel is too nice giving people write
access to the repo and allowing (if i'm not mistaken) them to push
without a review.  errors happen, that's life.  i suspect (or, rather,
hope) that 8 is just a stopgap from a guilty conscience and things will
eventually be improved :)  for what i've seen, the review does
eventually happen, but it's more often than not after the fact.

**Comment by jaor** [comment]
@minad just a quick note to let you know that i'm again using emacs 28 (today's master, compiled with native comp) and the corfu flicker i had observed (as well as this problem, as expected) is totally gone. i am pretty pleased :)
