### ISSUE TITLE
vertico-mode doesn't play nice with debbugs.el

### ISSUE THREAD

**Issue by Dickby** [minad/vertico#310]
With vertico-mode enabled, some debbugs.el commands are not working as intended:

debbugs-org-search and debbugs-gnu-search : 
these commands first prompt for a search phrase,
second they prompt for an attributes, third for an value for the chosen attribute.
The second and third prompts are repeated until nothing is entered for attribute,
that triggers the search.
With vertico-mode it's not possible to enter nothing as an attribute, because one candidate is alway selected.

debbugs-org-bugs and debbugs-gnu-bugs:
the functions are prompting for a comma seperated list of bug numbers, or an range.
With vertico-mode enabled, it's not working properly sometimes, because the completion results
seem to be not always available.

Thanks.

**Comment by minad** [comment]
> With vertico-mode it's not possible to enter nothing as an attribute, because one candidate is alway selected.

See the README regarding empty input.

> debbugs-org-bugs and debbugs-gnu-bugs:
the functions are prompting for a comma seperated list of bug numbers, or an range.
With vertico-mode enabled, it's not working properly sometimes, because the completion results
seem to be not always available.

`debbugs-org-bugs` uses a `completion-table-dynamic` in `debbugs-gnu-completion-table`. If you set the `completion-styles` to `(orderless basic)` or only `(basic)` it should work fine. But note that your input cannot be in Orderless style. You must use prefix completion, because of `completion-table-dynamic`.
