### ISSUE TITLE
Option to popup Vertico UI after [N] characters

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [minad/vertico#313]
If this is not already possible, I think it would be good idea to add an option to set a limit on how many characters must be typed to popup/activate Vertico UI.
I've noticed a bit of lag with commands which has more than ~5000 completion candidates, which is commonly a case with M-x command.
This option would work great with vertico-multiform feature, cause user could change minimum character limit based on how many completion candidates there are per command and based on their computer performance.
Also this reduces visual clutter, but my main concern is with performance.
The lag is really not that bad, but it's still visible when i open M-x command (for example), and when first few characters are typed.
P.S. Of course, i could set `completion-styles` to be more basic, so completions perform better, but i still would like to keep my fancy completion method.

**Comment by minad** [comment]
There is no point in doing this. You can already start typing even if Vertico isn't visible yet, since the computation is interruptible. But there are two possible solutions which may satisfy you:

- Alternative 1: `(advice-add #'vertico--setup :after #'redisplay)`
- Alternative 2: Define a custom completion style which doesn't compute candidates if the input is too short, see https://github.com/doomemacs/doomemacs/issues/6622#issuecomment-1306875744.

Please let me know what you think.

**Comment by minad** [comment]
Which completion style do you use, if I may ask. If you observe slowdown for 5000 candidates it is really slow (or your hardware is very old). Slowdown shouldn't happen below 20k or 50k candidates and I also don't use a recent notebook. See also https://github.com/axelf4/emacs-completion-bench.

**Comment by minad** [comment]
> (basic partial-completion substring initials flex)

Interesting. For empty input basic is used, which is as fast as it gets. Filtering will essentially reduce to copy-sequence.

> This feels a lot better to me, cause i see visual feedback immediately (mini-buffer prompt), even if it takes candidates to show up a bit later

Yes. The problem is that this leads to flicker for very fast completion commands. There is no silver bullet here unfortunatly. We cannot decide early on if redisplaying right away is the right thing.

> That is good that computation is interruptible, but just to be more clear, i meant that computation should only start when entering set amount of characters, cause, i thought that completion algorithm performs better if in input there are more characters, as opposed to 1 or 2, but i think i might be wrong here.

Of course it performs better if there is input. All I am saying is that it is unnecessary to add this feature to Vertico itself. You can either use immediate redisplay or implement a completion style which requires a certain input length.
