### ISSUE TITLE
Support ido style folder navigation

### ISSUE THREAD

**Issue by galeo** [minad/vertico#33]
Ivy supports [ido style folder navigation](https://github.com/abo-abo/swiper/wiki/ido-style-folder-navigation), which uses <kbd>C-j</kbd> to terminate immediately with the current value, and uses <kbd>RET</kbd> to continue to complete the directory. Is it possible to achieve this in vertico?

**Comment by minad** [comment]
Of course, that's possible with some elisp :) I have no plans to support such special commands in Vertico.

You can write a command which exits with the `file-name-directory` of the `minibuffer-contents` (C-j):

~~~ elisp
(defun vertico-exit-dir ()
  (interactive)
  (let ((dir (file-name-directory (minibuffer-contents))))
    (delete-minibuffer-contents)
    (insert dir)
    (exit-minibuffer)))
~~~

Similarly you can write another command which restarts the search session in that directory. But that maybe more difficult since this is more like an `embark-become` style command.

Maybe https://github.com/raxod502/selectrum/wiki/Ido,-icomplete(fido)-emulation can be used for inspiration? See also https://github.com/raxod502/selectrum/issues/498.

**Comment by minad** [comment]
See also https://github.com/minad/vertico/blob/main/extensions/vertico-ido.el

**Comment by galeo** [comment]
Thanks 👍
