### ISSUE TITLE
display problem with a long prompt containing multi-byte characters 

### ISSUE THREAD

**Issue by ilupin** [minad/vertico#343]
Hi, I find vertico doesn't display well when using `completing-read` with a long prompt containing multi-byte characters. Below is an example:

`(completing-read (make-string (- (/ (frame-width) 2) 1) ?😀) '("1" "2" "3"))`

![图片](https://user-images.githubusercontent.com/5555871/225495654-a12c37a3-fc6c-4645-bdb8-cc95a5ed7339.png)

As shown in the figure, the prompt is invisible.

The problem doesn't appear when I use a short prompt or a very long prompt, e.g. 
`(completing-read (make-string (frame-width) ?😀) '("1" "2" "3"))`
![图片](https://user-images.githubusercontent.com/5555871/225496481-0ae29d33-8815-4f1f-8d11-b4ccb9392ad1.png)

I'm using emacs 29 and vertico 1.2

**Comment by minad** [comment]
Oh, that looks awkward. It seems like a minibuffer horizontal scrolling bug in Emacs (minibuffer has been notoriously buggy in the past), maybe due to line truncation. Currently I disable truncate-lines in the minibuffer if the point is too far to the right:

https://github.com/minad/vertico/blob/3386763b717415840fd58929cc2ca056e0eb10d5/vertico.el#L617

This criterion doesn't trigger in this case. But it explains why it works for longer strings. As a workaround you can use an after advice of vertico--resize-window and there set truncate-lines to nil. Besides that I don't immediately see how we could improve the situation in Vertico. Suggestions welcome!

**Comment by ilupin** [comment]
Thanks! According to the code, the value of `(point)` is used as the width of input(?), which, I think, is incorrect for multi-byte characters (e.g. CJK). Actually I didn't find such display problem with long strings containing only ascii characters. How about computing the pixel width of strings? e.g.

`(< (car (window-text-pixel-size nil (point-min) (point) t))
                                (* 0.8 (window-pixel-width)))`

I test with some long strings and it seems works.

**Comment by minad** [comment]
The problem with window-text-pixel-size is that it may take overlays into account, or doesn't it. Vertico uses overlays for the candidate display.

**Comment by ilupin** [comment]
Thanks! I tried the latest code and it solves the issue. I don't find other problems yet.
