### ISSUE TITLE
Option to not move DEF to start of candidates?

### ISSUE THREAD

**Issue by muirdm** [minad/vertico#347]
If a custom sorting is in play (i.e. candidates' order is meaningful), would it make sense to not automatically move the default candidate to the beginning of candidate list? Instead, the caller of completing-read should just make the default the first candidate if it so desires (this is what consult-line already does).

I have my consult-line+isearch=abomination working perfectly except for this last quirk. I want the candidate/lines to maintain their absolute order from the file, so I don't want the current (i.e. default) line to move to the top of the candidates. I don't like the "relative" behavior of consult-line.

For a concrete proposal, can we expose the "default first" sorting behavior as part of `vertico-sort-function` stuff? Then a custom sort will automatically disable the default first behavior.

EDIT: I guess this would also conflict with vertico-preselect which doesn't support preselecting a default candidate in an arbitrary position.

**Comment by minad** [comment]
I have to reject this for now, but will probably revisit this again in the future, when I come up with compelling reasons. Vertico relies on moving the default since the first candidate is preselected in this case. We would also have to adjust the preselecting logic. See #346 for a related discussion and the [preselect-function](https://github.com/minad/vertico/tree/preselect-function) branch. I had long discussions about this and related issues with @gusbrs before.

I understand that you moved just recently to Vertico? Vertico is already widely used and stable, so I am growing less interested in adding support for specific hacks which are only useful for a handful of users. As I mentioned on the Consult issue tracker, I have to keep an eye on maintainability.

**Comment by gusbrs** [comment]
@muirdm  for the case of `consult-line` there is https://github.com/minad/consult/issues/287#issuecomment-1466158081, which may interest you.
