### ISSUE TITLE
FEATURE REQUEST: Persistent quick key labels

### ISSUE THREAD

**Issue by rswgnu** [minad/vertico#349]
I would like a mode where the quick keys inserted with quick-key-insert stay live as you move through choices within a vertico selection, so whether you move from item to item, scroll the list of visible items or move to a new directory in a file finding command, all the visible candidates stay labeled and selectable.  This would make the quick keys much more useful during navigation, rather than having to manually ask to insert them repeatedly.  Thanks for considering this.

**Comment by minad** [comment]
There are two answers:

1. Showing the keys always is not really useful since you have to press a key anyway such that quick keys are accepted afterwards. Furthermore this reflects the behavior of Avy.

2. We already have this feature, but it in form of `vertico-indexed-mode`. The indexed mode always shows the keys, but it might be a bit too limited. It only supports numbers. We also don't support direct minibuffer exit by pressing a single key, e.g., M-2. See #218 for anothe discussion. Patches improving `vertico-indexed-mode` are welcome.

**Comment by rswgnu** [comment]
Thanks for the feedback.
