### ISSUE TITLE
If the unobstructive mode is active, the current candidate won't get highlighted when switching style with multiform mode

### ISSUE THREAD

**Issue by bit69tream** [minad/vertico#359]
![vertico](https://user-images.githubusercontent.com/43259894/234724387-8d92be1c-c292-410d-9f3e-baea67ac4518.gif)

emacs - `GNU Emacs 29.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8) of 2023-04-15`
vertico - 1.3.

**Comment by minad** [comment]
This is intentional. `vertico-unobtrusive-mode` doesn't add an obtrusive (and unnecessary) highlighting, since only the topmost candidate is displayed. The braces/parenthese around the candidate change when you select the prompt. If you want to enable this mode only for a few command you should set `vertico-multiform-commands` or `vertico-multiform-categories`.
