### ISSUE TITLE
Hiding uninteresting file types

### ISSUE THREAD

**Issue by ndvanforeest** [minad/vertico#37]
I really like vertigo. Is it possible to hide certain file types? This is particularly useful when using latex, at least for me.

**Comment by minad** [comment]
Of course, Emacs (and therefore Vertico) supports that out of the box with `completion-ignored-extensions`.

**Comment by ndvanforeest** [comment]
Thanks. Great. I have to admit that I did not realize this from the manual of vertico. After years of using ido I simply forgot that I can use the same variable. Perhaps it would be helpful to include a line in the manual mentioning this.

**Comment by daviwil** [comment]
I think it would be good to have some kind of resource to show the kinds of things one might want to do and how to configure Emacs for it.  Maybe a Vertico wiki?  I'd also like to do a video on a more complete Vertico config at some point so this could be a great source of info for that.

**Comment by ndvanforeest** [comment]
Actually, I just watched the system crafters video on vertico, and that made me decide to give vertico a try. As for me, an example on how to configure hidden files would suffice, something similar to the example of using orderless alongside vertico. But with your hint, I ll just copy my stuff from the Ido configuration. 

Here is the link to the YouTube film, https://youtu.be/XoI1XPqXQ90.

**Comment by minad** [comment]
@daviwil I activated the wiki, but I am not sure if a separate Vertico wiki is really needed. Since Vertico is built on top of default completion, everything documented in https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html applies. Generally I prefer if the READMES are the basis for a canonical configuration. If one adds a full-blown Vertico+Consult+Orderless+Embark configuration to the wiki it will soon get outdated. Then I don't see Vertico as the central component here, I am not even sure there is one :)

Note that there is the [Consult wiki](https://github.com/minad/consult/wiki) and the [Embark wiki](https://github.com/oantolin/embark/wiki).

The things which come to my mind for a Vertico wiki are the following:

* Collecting some Vertico-specific minibuffer commands (documenting e.g. #33 or #35)
* Documenting alternative display modi which are not supported ootb in Vertico, e.g., child frames as provided by mini-frame or posframe
* Maybe some advanced tweaks modifying some internals using advices etc?

**Comment by ndvanforeest** [comment]
Your idea to refer to the emacs manual makes good sense to me. If the vertico readme would have said this

> Since Vertico is built on top of default completion, everything documented (such as hiding uninteresting files) in https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html applies.
> 
then that would have sufficed to help me realize that vertico indeed follows the completion api of emacs. (Of course, the current readme says this, but I failed to realize the depth of the remark).
