### ISSUE TITLE
Infinite redisplay_internal loop with yascroll

### ISSUE THREAD

**Issue by whame** [minad/vertico#376]
Running the following with `emacs -Q -l test.el`

```elisp
;;; test.el

(add-to-list 'load-path "yascroll")
(add-to-list 'load-path "vertico")

;; Vertico needs this.
(add-to-list 'load-path "compat")

(require 'yascroll)
(require 'vertico)

(global-yascroll-bar-mode t)

(vertico-mode)

;; Any dummy file that would be sufficiently big to show the scroll bar.
(find-file "/proc/kallsyms")

(split-window-right)

(call-interactively 'execute-extended-command)

;; Now press C-g (`abort-minibuffers`). Watch the CPU usage of the process
;; (should be very high). gdb shows that `run_window_change_functions()` is
;; called repeatedly.
```

seems to cause an infinite calls to `redisplay_internal()` in Emacs.

I can not trigger this behavior without activating Vertico. Therefore, it seems like there is some interference here between [yascroll](https://github.com/emacsorphanage/yascroll) and Vertico.

Now, it could of course be a bug in yascroll only. Do you have any idea what is going on here? Any pointers would also be helpful!

**Comment by minad** [comment]
I am not familiar with Yascroll, so I cannot really tell what is causing this. Considering the side of Vertico, I am not aware of any wrong doing related to scrolling. Vertico should not lead to the creation of scrollbars in the miniwindow, since Vertico resizes the miniwindow according to the content. Maybe Yascroll can be configured to avoid interfering with the miniwindow? If this is not possible, I suggest that you use either Vertico or Yascroll but not both together given the incompatibility.

**Comment by minad** [comment]
See also https://github.com/emacsorphanage/yascroll/issues/37, which is probably related.
