### ISSUE TITLE
FEATURE REQUEST: 

### ISSUE THREAD

**Issue by rswgnu** [minad/vertico#377]
I would like to be able to do two things with vertico-mouse.el when given only a mouse click event as input:

1. Have a function that given that event, returns the data for the item clicked upon.  This would include its index number for feeding to other vertico functions.

2. Have a function that selects the item and sends it to the minibuffer as input.

These would make mouse control of vertico from other packages much simpler, I believe.  Since none of the functions take mouse events as input right now, it is difficult to interface with.

**Comment by minad** [comment]
Indeed, we could create a more accessible API, but that's not really the goal of vertico-mouse.

If I recall correctly I tried your proposed approach before but it wasn't reliable. I tried to attach a property to the displayed candidate strings (e.g. the index) and then used a common command to handle the click. The common command should extract the index and act on the corresponding candidate. In the end I went with the current solution with the attached keymap per candidate and commands which capture the index in a closure.

I don't have plans to change this right now. But of course feel free to experiment with your proposed approach and create a patch or proof of concept. I would be happy to change this, since it would certainly be more elegant and flexible. The main requirement is that the result works reliably.

**Comment by minad** [comment]
I just gave this another quick try and this time it seemed to function as desired. I like this  more than attaching a keymap to the candidates. Let's see if it works for other users too. Can you please give this a thorough test? If other users are around here, I'd also appreciate some testing. Thanks!
