### ISSUE TITLE
FEATURE REQUEST: Select a candidate line based on character position in completion buffer

### ISSUE THREAD

**Issue by rswgnu** [minad/vertico#378]
I would like to be able to select an arbitrary position in the completion buffer and have that position selected as the current candidate line.  Is there any way to do this?  Really asking if there is a way to convert a buffer position to a vertico--index?  This would then allow me to run commands that move point and then select whichever candidate happens to be at that point without knowing ahead of time what I want to select or how to narrow the selections.

**Comment by minad** [comment]
No, that's not directly possible. You can use an event and convert it to the overlay string plus position inside that string. The thing that is missing is the index of the candidate, since Vertico doesn't attach metadata to the displayed string by default. But I've now added such a mechanism to vertico-mouse, see https://github.com/minad/vertico/commit/cd039f6a3b36a74aaf1503ade87394414960c459 and https://github.com/minad/vertico/issues/377#issuecomment-1619016708. Please give that a try!

**Comment by rswgnu** [comment]
Will give it a try, thanks.  The conversion from the event position to the
index is what I wanted/needed.  -- rsw
