### ISSUE TITLE
(feature request) Vertico equivalent of ivy-resume/selectrum-repeat? 

### ISSUE THREAD

**Issue by mclearc** [minad/vertico#38]
Selectrum has a command `selectrum-repeat` which lets the user open the mini buffer with the last completed command. The function is here: https://github.com/raxod502/selectrum/blob/909f614319dad6c7eeebb76b2c2501e8215718ea/selectrum.el#L2940. It's basically a version of ivy-resume. Any chance for something like this in vertico?

**Comment by minad** [comment]
No, such a command should not be part of Vertico, since such a feature is not directly related to the UI.

At some point I wrote the small package Uchronia (https://github.com/minad/uchronia/blob/main/uchronia.el), which maintains an input history for completion commands. There are the commands `uchronia-repeat` and `uchronia-select`. I am not sure if this `uchronia-repeat` command works as you would expect, maybe it does not even work at all.

Overall I didn't find the feature useful enough so this Uchronia package did not crystallize into a released package. This functionality is also a bit too small for its package? Furthermore it does not really fit into Embark nor does it fit into Consult.

**Comment by minad** [comment]
There are also packages like https://github.com/PythonNut/historian.el. Maybe you find a package which already supports the functionality you are interested in?

**Comment by minad** [comment]
@mclearc I tested my Uchronia snippet, revised and simplified it slightly. I think this should work mostly for your purposes.

**Comment by mclearc** [comment]
Fantastic -- thanks for letting me know! Also,  I noticed one typo in the README for Uchronia: you use `uchronia-restart` where I think you mean `uchronia-repeat`. Thanks again!

**Comment by minad** [comment]
Thanks, I corrected that.

**Comment by minad** [comment]
See https://github.com/minad/vertico/blob/main/extensions/vertico-repeat.el
