### ISSUE TITLE
Performance issue with `vertico--truncate-multiline`

### ISSUE THREAD

**Issue by ksqsf** [minad/vertico#387]
Currently, `vertico--truncate-multiline` first does a bunch of regex replacements on the candidate string and then truncate it, but this creates severe performance degradation with `consult-yank-pop`: first copy a large file, press M-y, and it feels extremely sluggish to move up/down in the candidate list.

Truncating the input first fixes this performance degradation: 

```elisp
(defun vertico--truncate-multiline-advice-limit-input-length (oldfun cand max-width &rest _)
  (funcall oldfun (substring cand 0 (min (length cand) (* 2 max-width))) max-width))
(advice-add 'vertico--truncate-multiline :around #'vertico--truncate-multiline-advice-limit-input-length)
```

I'm not sure if this is the best solution (I don't have deep understanding of vertico and consult), and you could probably implement a more appropriate fix in vertico. Thanks!

**Comment by minad** [comment]
I added your fix. The solution is not great though since it yields wrong results for example if the string starts with many spaces. However it doesn't seem worth it to write a more sophisticated version. I also notice that other functionality like Consult preview is also getting quite sluggish for extremely large candidates.
