### ISSUE TITLE
rgrep problematic completion

### ISSUE THREAD

**Issue by non-Jedi** [minad/vertico#388]
This may just be a matter of me holding it wrong but when `M-x rgrep` prompts for "Search for x in files matching wildcard (default x):", I frequently make the mistake of accepting the default after typing in my actual pattern because you need to call `vertico-exit-input` instead of just `vertico-exit`.

Should this be mentioned as a "problematic command" similar but slightly different to ["Submitting the Empty String"](https://github.com/minad/vertico#submitting-the-empty-string), or is there something else I'm doing wrong?

- GNU Emacs 29.0.92 (build 2, x86_64-unknown-linux-gnu, X toolkit, cairo version 1.16.0) of 2023-07-30
- Vertico version: GNU ELPA commit 5cb799e (2023-08-10 00:00:30)

**Comment by minad** [comment]
Hi, the usage is similar to `find-file` where you can enter a wildcard pattern like `*.org` to open all Org files in the directory. However in order to do that one also has to submit the prompt. I don't consider this behavior problematic.

The commands mentioned in the Vertico README are of a different quality, they are actually broken. For example in order to make a command submit the empty string by default one simply has to pass "" as default argument to `completing-read`, since otherwise Vertico has no chance to distinguish intentional and unintentional empty completion.

**Comment by non-Jedi** [comment]
Okay. That makes sense. Thanks!

**Comment by minad** [comment]
I expanded the README slightly regarding wildcards. The information was already there but maybe not explicit enough.
