### ISSUE TITLE
tramp mounted archives cause switch-to-buffer to hang

### ISSUE THREAD

**Issue by andreyorst** [minad/vertico#66]
I'm getting this error in `*Messages*` buffer:

```
Error in post-command-hook (vertico--exhibit): (error "Process *tramp/archive file%3A%2F%2F%2Fusr%2Flib%2Fjvm%2Fjava-1.8.0-openjdk-1.8.0.292.b10-4.fc34.x86_64%2Fsrc.zip* not running")
```

**Comment by minad** [comment]
This sounds as if the tramp connection is dead. It does not sound like a Vertico bug to me. If the completion table throws an error, Vertico cannot do much about this. Do you use `switch-to-buffer` or `consult-buffer`?

**Comment by andreyorst** [comment]
I forgot to mention that this is a local file

**Comment by minad** [comment]
I don't understand what you are doing here tbh. Please don't assume specific knowledge of your configuration. Ideally I need a minimal reproducible init.el configuration which can be started with emacs -Q in order to reproduce an issue. But I cannot help you with CIDER issues since I am neither a CIDER nor a Clojure user. Maybe the CIDER maintainers can be of help? I assume you add the archive to the variable `cider-jdk-src-paths` as shown in (http://docs.cider.mx/cider/config/basic_config.html)? Note that they are not using archives here, but an unpacked source directory.

~~~ elisp
(setq cider-jdk-src-paths '("~/java/clojure-1.8.0-sources"
                            "~/java/openjvm-8-src"))
~~~

**Comment by minad** [comment]
The CIDER docs also say

> It’s possible to point cider-jdk-src-paths to jar or zip files, but extracting them is better since you can use features like ag or dired-jump.

But in that case you should probably not use a `file://...` url, but the plain path to the file?

**Comment by andreyorst** [comment]
> I don't understand what you are doing here tbh.

I've came to the maintainer to discuss the problem. You know, I give you a bit of info, you ask a bit more - I give a bit more, I mean, I also don't know what info do you really need, right? You don't have no template to fill so I've just placed here the error that bothers me.

No need to be harsh, just ask in particular.

> Note that they are not using archives here, but an unpacked source directory.

Yes, but the default value is the `.zip` archive.

CIDER uses TRAMP by default, because REPL connection may not be local, so TRAMP is preferred. I'm in no position to judge this decision, I just know that this causes problems with this package.

> But in that case you should probably not use a `file://...` url, but the plain path to the file?

[I'm not](https://gitlab.com/andreyorst/dotfiles/-/blob/7fd027ac2b7f943e23ddee4dd432812b975422fc/.config/emacs/init.el#L1478-1483)

---

I'll submit the minimal repro case later.

**Comment by minad** [comment]
> I've came to the maintainer to discuss the problem. You know, I give you a bit of info, you ask a bit more - I give a bit more, I mean, I also don't know what info do you really need, right? You don't have no template to fill so I've just placed here the error that bothers me.

This back and forth costs a lot of time. I appreciate a more detailed bug report. That's all. See for example https://github.com/minad/consult/#bug-reports for how a good bug report is supposed to look. For example you did not even mention CIDER in your initial report.

> CIDER uses TRAMP by default, because REPL connection may not be local, so TRAMP is preferred. I'm in no position to judge this decision, I just know that this causes problems with this package.

This is weird. Why is it opening a local file via TRAMP? Please ask the the CIDER maintainers about this. While the error occurs in the Vertico callstack, it also occurs deeper down in the completion table.

**Comment by andreyorst** [comment]
I think you're right, this has nothing to do with vertico, I've managed to reproduce it without your package. Vertico just helped me notice this error, so sorry for the noise

**Comment by minad** [comment]
Thanks! That's a very good approach to narrow down the issue - check if it also occurs with default completion/Selectrum/Ivy or sth else. I should have asked that right away. Sorry for sounding harsh - this was not my intention. 

Probably I should add a section about the information which would be good to have supplied with a bug report. As you mentioned I could also use these bug report templates as proposed by GH. Personally I dislike those. If a user already did a deeper investigation and some debugging, the template seems useless. I like to have as much information as possible but I don't want to press the user to fill out such a form. 

In your particular case, the issue is also that the error occurs in the `post-command-hook`. Unfortunately `post-command-hooks` are treated specially in Emacs, they *disable debugging*! On the one hand this is good since Emacs stays usable, on the other hand it makes it much harder for the user to produce a useful stack trace. I've considered before to add a catch-all in `vertico--exhibit` which prints out all the needed information.

**Comment by andreyorst** [comment]
> check if it also occurs with default completion/Selectrum/Ivy 

The thing is - I was using Ivy previously, and it didn't had this issue. So I've naturally assumed that the issue is in this package

Thanks again for the help!

**Comment by minad** [comment]
> The thing is - I was using Ivy previously, and it didn't had this issue. So I've naturally assumed that the issue is in this package

Of course, this is generally a reasonable assumption to make if you install something new. However Vertico really tries to cut away as much as possible relying only on the built-in facilities. The goal is to reduce the bug surface as much as possible and to end up something which can be maintained without much effort in the long term. If this works out remains to be seen :shrug: 

Ivy and other UIs replicate quite some functionality themselves - this can then lead to bugs being shadowed. Furthermore I am generally avoiding to add workarounds here. I am only doing this when the bugs cannot be fixed in another way - let's say if the bug is in some core Emacs functionality itself.
