### ISSUE TITLE
Issue with vertico when completing ssh hostnames

### ISSUE THREAD

**Issue by plattfot** [minad/vertico#68]
I'm having some issues completing ssh hostnames with `vertico` when using `orderless`. Works fine when I use `selectrum` and `orderless`.

Issue is when I type in `/ssh:` I only get a list of other tramp prefix commands, i.e `/scp:` and `/scpx:`. Expected behavior is to get a list of hostnames I have connected to before, prefixed with `/ssh:`.  It works as expected when I'm not using `orderless`.
 
# Repro
## Versions
`vertico-0.12`
`orderless-0.6`
`emacs-28.0.50`/`emacs-27.2`
## Steps
Save to `/tmp/init.el`
```     
(require 'orderless)
(require 'vertico)
(setf completion-styles '(orderless))
(vertico-mode)
```
Run `emacs -Q -l /tmp/init.el`, run `find-file` and type `/ssh:` and you should see a list of just `/scp` and `/scpx`

**Comment by plattfot** [comment]
Bah, forgot to test with only `orderless` (using emacs' default completion system). And can conclude that this is a bug in `orderless` and not `vertigo`.

Seeing the same issue with:
```
(require 'orderless)
(setf completion-styles '(orderless))
```
Closing this issue. Sorry for the noise!

**Comment by minad** [comment]
It seems that only the `basic` completion style shows hostnames. My recommendation is to define a special completion style `orderless-remote` which falls back to `basic` for remote completion:

~~~ elisp
(defun orderless-remote-try-completion (string table pred point)
  (if (string-match-p "\\`/[^/|:]+:" (substitute-in-file-name string))
      (or (completion-basic-try-completion string table pred point)
          (orderless-try-completion string table pred point))
    (orderless-try-completion string table pred point)))

(defun orderless-remote-all-completions (string table pred point)
  (if (string-match-p "\\`/[^/|:]+:" (substitute-in-file-name string))
      (or (completion-basic-all-completions string table pred point)
          (orderless-all-completions string table pred point))
    (orderless-all-completions string table pred point)))

(add-to-list
 'completion-styles-alist
 '(orderless-remote orderless-remote-try-completion orderless-remote-all-completions nil))

(setq completion-category-overrides '((file (styles orderless-remote))))
~~~

Alternatively you can just define to use `basic` in combination with `orderless`, but this may be undesired, since it will affect every file completion, not only remote files.

~~~ elisp
(setq completion-category-overrides '((file (styles basic orderless))))
~~~

**Comment by minad** [comment]
@iyefrat You are probably interested in this one too. This is a general problem with some completion tables, which assume that the `basic` completion style is used. See also https://github.com/minad/vertico#problematic-completion-commands.
