### ISSUE TITLE
Documented enabling of vertico for completion-at-point didn't work. 

### ISSUE THREAD

**Issue by rileyrg** [minad/vertico#73]
The documentation here : https://github.com/minad/vertico specified this code to enable vertico for point completion in buffer:-

```
;; Use `consult-completion-in-region' if Vertico is enabled.
(add-hook 'vertico-mode-hook (lambda ()
                               (setq completion-in-region-function
                                     (if vertico-mode
                                         #'consult-completion-in-region
                                       #'completion--in-region))))
```

It didn't work for me, I didn't look too much into it but I had checked my hook was properly set. This did work for me: setting it in my vertico use-package:-

  ```
(use-package vertico
    :init
    (vertico-mode +1)
    (setq completion-in-region-function #'consult-completion-in-region)
    (setq vertico-cycle t)
    )
```

It looks like the problem is that that code doesnt work with the provided use-package since vertico-mode is enabled in the :init so the hook lambda isn't triggered.

cheers.

**Comment by minad** [comment]
Well, the hook must be installed before enabling vertico-mode.

1. require vertico
2. Add hook
3. Enable vertico

Your solution is also fine but then consult-completion-in-region may be active even when vertico is disabled.

**Comment by rileyrg** [comment]
Sure, but just pointing out that the solution in the doc is not compatible with the use-package on the same page. BTW I tried using :hook in the use package as I assumed that would be set up and it still didnt work. I moved the vertico-mode to :config and still not. I'll take a peek later when I have more time.

**Comment by minad** [comment]
Putting `add-hook` in the `:init` section should work.

~~~ elisp
:init
(add-hook 'vertico-mode-hook (lambda ()
                               (setq completion-in-region-function
                                     (if vertico-mode
                                         #'consult-completion-in-region
                                       #'completion--in-region))))
(vertico-mode)
~~~

**Comment by rileyrg** [comment]
Yup, it does. Silly of me not to do that - let my try a ":hook" solution.

**Comment by rileyrg** [comment]
ok, use-package :hook isn't setup before :init. So add-hook in :init is the only solution for use-package. 

*Doesnt work*:-

  ```
(use-package vertico
    :custom
    (vertico-cycle t)
    :init
    ;; Use `consult-completion-in-region' if Vertico is enabled.
    (vertico-mode)
    ;;(setq completion-in-region-function #'consult-completion-in-region)
        ;; (add-hook 'vertico-mode-hook (lambda ()
        ;;                              (setq completion-in-region-function
        ;;                                    (if vertico-mode
        ;;                                        #'consult-completion-in-region
        ;;                                      #'completion--in-region))))

    :hook
     (vertico-mode . (lambda ()
                                     (setq completion-in-region-function
                                           (if vertico-mode
                                               #'consult-completion-in-region
                                             #'completion--in-region))))
    )
```

**Comment by minad** [comment]
Maybe using `:hook`, `:demand t`, and `vertico-mode` in `:config` works too?

**Comment by minad** [comment]
Maybe I will move away from `use-package` at some point. It works well for small, isolated, declarative package configurations. But it somehow doesn't scale to more complicated scenarios, e.g., well when configuring integration packages or when writing configurations which depend on multiple packages being loaded. The simple scenarios are probably solved easily with a handful of macros. This is how the next personal use-package starts ;)

**Comment by rileyrg** [comment]
TBH I would have expected :hook to do its stuff before a mode call in :init ;)

**Comment by daviwil** [comment]
@minad I'm already plotting a move away from `use-package` to a more straightforward config style.  In practice, I'm not sure if `use-package`'s brevity is worth the load ordering complexity.  It'd probably make more sense to use single-purpose functions or macros to accomplish some of the useful things it does (more concise hook registration, setting keymap bindings, etc).

Not the purpose of this issue, but since I saw you mention abandoning `use-package` I thought I'd give my perspective :)

**Comment by minad** [comment]
>  It'd probably make more sense to use single-purpose functions or macros to accomplish some of the useful things it does (more concise hook registration, setting keymap bindings, etc).

Yes, indeed. I feel the same way. The conciseness of use-package can probably be replicated with a handful of simple helpers. 

On the other hand - there are full blown Emacs distributions like Doom which are based on use-package, so it scales reasonably well. Generally I try to not stuff too much into my config, moving all the non-trivialities to separate packages. Therefore I am not too worried if my configuration is not super clean. But use-package was certainly a step in the right direction for a more structured configuration :)

**Comment by daviwil** [comment]
`use-package` definitely scales well enough, though I think it obscures the underlying mechanics of configuring Emacs via Emacs Lisp to the extent that I'm unsure whether it is a benefit or a liability to people who are learning Emacs.  

At this point I almost think it's better for someone to learn the basics of Emacs Lisp through configuring Emacs using the built-in functions instead of a convenience macro.  I've been considering remaking my Emacs From Scratch tutorial like that and maybe only bring `use-package` into the picture much later, if at all.

**Comment by minad** [comment]
@daviwil What do you think about [Leaf](https://github.com/conao3/leaf.el) btw? I also looked a bit into how use-package could generally be simplified. I still think some of the use-package abstractions are very reasonable - there is a need for a dsl to specify binds, hooks, auto-modes, interpreters etc, which are marked as autoloaded and added to the corresponding lists/bound to the keys. My main criticism is that use-package generates too complicated code. Leaf in contrast seems to generate relatively code. I just found leaf now, and before I played around with a handful of macros myself and ended up with something very similar to Leaf (stripped down, only with :hook, :bind, :mode, :preface and the main block).

**Comment by minad** [comment]
~~~ elisp
(pkg! marginalia
  (:bind "M-A" marginalia-cycle)
  (marginalia-mode))

(pkg consult
  (:bind
   "C-c m" consult-mode-command
   "C-c h" consult-history
   "C-c k" consult-kmacro
   "C-c b" consult-bookmark
   ...)
  (:bind isearch-mode-map
         "M-e" consult-isearch
         "M-s e" consult-isearch
         "M-s l" consult-line)
  (:hook completion-list-mode consult-preview-at-point-mode)
  (:preface
   (setq register-preview-delay 0
         register-preview-function #'consult-register-format)
   (advice-add #'register-preview :override #'consult-register-window))
  (consult-customize
   consult-theme
   :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-file consult--source-project-file consult--source-bookmark
   :preview-key (kbd "M-."))
  (setq consult-narrow-key "<")
  ...)
~~~

**Comment by daviwil** [comment]
I haven't looked at Leaf very deeply yet because on the surface it looks very similar to `use-package`.  I think my main complaint with any all-encompassing macro is that it creates a special syntax which brings people further away from the actual underlying Emacs Lisp code.

I think what I'd prefer to see specifically for something like key bindings is a built-in macro called `define-key*` which allows you to do multiple key bindings for a single key map all at once so that it doesn't move too far away from the real `define-key` function.  

Instead of encouraging new users to write declarative pseudo-configuration expressions, I think it might be more enlightening to tell them "the configuration is code, but it's not hard to write".  It might be the fastest way to convince someone that Emacs isn't just some pre-canned tool but a fully moldable environment that they can enjoy using.

I could be wrong about that though :)  Your syntax looks nice and simple, at any rate!

**Comment by minad** [comment]
> I think what I'd prefer to see specifically for something like key bindings is a built-in macro called define-key* which allows you to do multiple key bindings for a single key map all at once so that it doesn't move too far away from the real define-key function.

I agree. It may also be useful to support string keybindings instead of only the primitive keys from `define-key`. Very quickly one will end up with something like bind-key...

> Instead of encouraging new users to write declarative pseudo-configuration expressions, I think it might be more enlightening to tell them "the configuration is code, but it's not hard to write". 

That's right. However it may also be good to show patterns which allow to write configurations efficiently, in a form which enables lazy loading and quick startup. Use-package supports many different very special scenarios (lazy loading keymaps), which are better coded explicitly. It makes sense to cut away these layers of complexity. For beginners it may be better to go bottom up and start first with the explicit configuration. But I would not discourage introducing helper macros. I guess one ends up with a DSL, even if you try to strip it down as much as possible.
