### ISSUE TITLE
Do vertico-next from outside minibuffer, with consult-line?

### ISSUE THREAD

**Issue by ave-63** [minad/vertico#82]
I am using `evil` and `consult-line`. I like having the matching lines show up in the minibuffer, but I miss just pressing n using the regular `evil-ex` search to go to the next match. With `consult-line` I have to go back and forth between the minibuffer (to do `vertico-next`) and regular buffer (to edit).

I tried writing a little function:

    (evil-define-key 'normal 'global (kbd "n") 'ben/consult-line-next)
    (defun ben/consult-line-next ()
      (interactive)
      (let ((og-window (selected-window)))
        (select-window (minibuffer-window))
        (vertico-next 1)
        (select-window og-window)))

This doesn't quite work, because it doesn't activate the consult preview to move me to the next match, and doesn't even show anything happening in the minubuffer. But then when I really switch to the minibuffer, the minibuffer and preview suddenly show that `vertico-next` has happened.

Any idea how to implement this properly? I imagine it would be handy for other consult functions too.

**Comment by minad** [comment]
@ave-63 Can you explain this a little bit more in detail? I think this is exactly the issue reported by @akagr in #318. The question is - do you want to move to the next match *after* closing the minibuffer, since this is not possible without quite some effort. I think @akagr explicitly asked for moving after pressing RET.

Of course it is easy to implement support for moving to the next match while the minibuffer is still open. You can try this prototype:

~~~ elisp
(global-set-key (kbd "C-.") #'vertico-next-from-outside)
(global-set-key (kbd "C-,") #'vertico-previous-from-outside)

(defun vertico-next-from-outside ()
  (interactive)
  (with-selected-window (active-minibuffer-window)
    (vertico-next)
    (vertico--exhibit)
    (when consult--preview-function
      (funcall consult--preview-function))))

(defun vertico-previous-from-outside ()
  (interactive)
  (with-selected-window (active-minibuffer-window)
    (vertico-previous)
    (vertico--exhibit)
    (when consult--preview-function
      (funcall consult--preview-function))))
~~~

Of course this should be generalized a bit. It would be nice to have a function `send-to-minibuffer`, which properly executes the command (or keybinding) in the minibuffer and runs all the post command hooks.

~~~ elisp
(defun down-from-outside ()
  (interactive)
  (send-to-minibuffer [down]))

(defun up-from-outside ()
  (interactive)
  (send-to-minibuffer [up]))
~~~

**Comment by minad** [comment]
The `send-to-minibuffer` is easily possible using `execute-kbd-macro` :)

~~~ elisp
(global-set-key (kbd "C-.") #'down-from-outside)
(global-set-key (kbd "C-,") #'up-from-outside)

(defun down-from-outside ()
  (interactive)
  (with-selected-window (active-minibuffer-window)
    (execute-kbd-macro [down])))

(defun up-from-outside ()
  (interactive)
  (with-selected-window (active-minibuffer-window)
    (execute-kbd-macro [up])))
~~~

**Comment by ave-63** [comment]
Thank you! `down-from-outside` and `up-from-outside` work great. Slightly off topic, but this inspired me to write a couple other related commands that I will put here in case anyone finds them useful:

    (global-set-key (kbd "C-S-g") 'ben/quit-minibuffer)
    (defun ben/quit-minibuffer ()
      "Quit the minibuffer from anywhere."
      (interactive)
      (with-selected-window (active-minibuffer-window)
        (execute-kbd-macro (kbd "C-g"))))

    (global-set-key (kbd "s-i") 'ben/to-and-fro-minibuffer)
    (defun ben/to-and-fro-minibuffer ()
      "Go back and forth between minibuffer and other window."
      (interactive)
      (if (window-minibuffer-p (selected-window))
	  (select-window (minibuffer-selected-window))
        (select-window (active-minibuffer-window))))

**Comment by minad** [comment]
Note that you can also use `ESC ESC ESC` to quit from anywhere, but it is a bit less convenient than your binding. You could also rebind `keyboard-escape-quit`.

**Comment by minad** [comment]
@ave-63 What do you think, can this be closed? I wonder if such a move from other window feature should be provided by consult-line somehow. Does swiper provide this out of the box? In any case you may want to document this in the wiki: https://github.com/minad/vertico/wiki.

**Comment by ave-63** [comment]
@minad Definitely can be closed. I would use `keyboard-escape-quit` but it often closes all of the windows except the selected one. I haven't used swiper so I'm not sure about it's features. I will try to add these four functions to the wiki later today or tomorrow!

**Comment by ave-63** [comment]
@minad Definitely can be closed. I would use `keyboard-escape-quit` but it often closes all of the windows except the selected one. I haven't used swiper so I'm not sure about it's features. I will try to add these four functions to the wiki later today or tomorrow!
