### ISSUE TITLE
Have next/previous group respect vertico-cycle

### ISSUE THREAD

**Issue by Koekelas** [minad/vertico#91]
What it says on the tin, have `vertico-{next|previous}-group` cycle only when `vertico-cycle` is truthy. This differs from having both cycling and non cycling versions of the commands discussed in #63 in that it reuses the existing commands and customization. My use case? I'm easily disoriented. Don't feel pressured to implement anything, the current implementation doesn't seem to be readily accommodating.

On an unrelated note, I've been using Vertico for a couple of months now and I enjoy it. Thank you for your time.

**Comment by minad** [comment]
> On an unrelated note, I've been using Vertico for a couple of months now and I enjoy it. Thank you for your time.

Thanks!

> What it says on the tin, have vertico-{next|previous}-group cycle only when vertico-cycle is truthy. 

I've considered this when we discussed #63, but rejected it since cycling of candidates should not be tied to the cycling of the groups. I am using `vertico-cycle=nil` but still enjoy cycling the groups. However one could still add a `vertico-cycle-group` customization option, but adding all these different variants will only lead to feature bloat.

As argued in #63, the group cycling is strictly more powerful than the simple group movement commands, since the cycling variants retains the topmost groups even when you continue to filter. This is valuable, you can first cycle to the desired group (e.g., in `consult-buffer`) and then filter. For these reasons I don't want to support both group movement command variants. As for the disorientation - the old group commands should still work, so you should be able to use them in your configuration as is. In that sense the old commands are unproblematic and non-intrusive, while the newer group cycling commands require a much tighter integration with the rest of Vertico. But despite their intrusiveness I decided on the cycling commands - since they are so much more powerful.

**Comment by Koekelas** [comment]
> As argued in #63, the group cycling is strictly more powerful than the simple group movement commands, since the cycling variants retains the topmost groups even when you continue to filter.

Yes, certainly desirable, I did not consider that. In a way similar to my "issue" with `consult-line`. Either the first candidate is the first match after point (but later candidates may be earlier matches) or the first match in the document (but the search starts from the top of the document). Still, thanks for elaborating your decision.

**Comment by minad** [comment]
Regarding consult-line, I added different highlighting for the wrapped around lines (https://github.com/minad/consult/commit/4ba5ad1946541a709bad1f0e6f1a2fef5df9d7ae). Hopefully this helps a bit to reduce the confusion with the wrapping.

**Comment by Koekelas** [comment]
Excellent! A couple of days ago, I made a note "investigate erroneous line number fontification consult-line". Now I can scratch that. You're not dealing brithest here.

**Comment by minad** [comment]
Is it more confusing than before?

**Comment by Koekelas** [comment]
It's neither more nor less confusing, I didn't get it. If the question is, is there a more intuitive way to visualize the transition? Perhaps a horizontal separator similar to groups? I have no idea how much work that would be, as it would be undesirable when `consult-line-start-from-top` is truthy.
