### ISSUE TITLE
Shadowed file name interferes with completion display in find-file

### ISSUE THREAD

**Issue by mohkale** [minad/vertico#97]
See [here](https://asciinema.org/a/FhcMga6OvY0A91fznJAMSQCNa).

The gist of my issue is that sometimes vertico seems to prefix the current shadowed file-name in the current completion candidates.

For example: `.config/dotfiles/bin/~/.config/ `.

**Comment by minad** [comment]
First, note that you can disable shadowed file paths by enabled vertico-directory-tidy (You probably know.)

I've observed this too. Sometimes I still see the shadowed name prefixed when entering a path like "~/.config/~man". Then the file completion table returns a candidate "/.config/~man", where ~man is username completion.

When I type "~/.config/~man/" (add the final slash) the reported completion candidates are the files in the ~man user directory, which is correct.

So the problem here is that Emacs thinks that the username is "/.config/~man" instead of only the "~man". It is an Emacs bug. I close it here. Should still report it upstream.

**Comment by minad** [comment]
Easy reproducible for reference:

~~~ elisp
(all-completions "~/.config/~man" #'read-file-name-internal) ;; returns ("/.config/~man")
~~~

**Comment by minad** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=49777
