### ISSUE TITLE
Do I miss something about how to activate the extensions

### ISSUE THREAD

**Issue by spiderbit** [minad/vertico#98]
I successfully installed and configured vertico-directory extensions copy/pasting the code from the Readme and ad "ensure: nil" because I set somewhere ensure always.

But then I tried to setup indexed / buffer and flat, one by one, downloaded it in my load path, only used:
```
(use-package vertico-indexed
  :ensure nil)
```
probably would have to add something like :setup (vertico-indexed-mode 1)

But activated them manually, but nothing happens. Do I need to setup some hooks or is something wrong with my setup? Neither do I see numbers before the entries (indexed), nor do I see open a separate buffer (buffer) nor does it go horizontal (flat).

**Comment by minad** [comment]
Do you use the newest Vertico? This could be a problem, not the released version, but the latest commit.

Try it the simple way:

1. Put the package in a directory on your `load-path`
2. (require 'vertico-indexed)
3. (vertico-indexed-mode)

Then it should work. The same with `vertico-buffer`, `vertico-mouse`, `vertico-flat` and `vertico-reverse`. For `vertico-quick` you have to bind some keys. I hope this helps!

**Comment by spiderbit** [comment]
yes loading the file from the repos directly did work, yet I am still a bit confused:
1. the flat thing is only showing 1 commend, not like ido or smex sidewards multiple options.
2. indexed just does nothing it seems
3. buffer just kind of looks like it freezes but when I press enter the first selection happens.

Is there with buffer some requirements with resolution test it on my netbook 1024x600?
With indexed do I have to do something else then activate it?

**Comment by minad** [comment]
It seems that there is something wrong with your config. All these packages work fine in my configuration. This is:

1. Flat shows multiple options side wards
2. Indexed shows indexes
3. Buffer does not freeze for me

Please try to reproduce your issue with emacs -Q on Emacs 27 or Emacs 28. Load vertico.el and vertico-*extension*.el from the repository, turn on the extension.

**Comment by spiderbit** [comment]
Yes with Emacs -Q everything works, but it's not really something wrong, ido and ivy both work fine... so it must be some incompatibility have to load then peace by peace or like git bisect till I find the incompatibility.

But one question, is there a hidden keyconfig with "indexed" I see the numbers, but how can I chose those? Ctrl+3, only 3 or f3 or what? I assume the number is not there just for estetics?

About my setup use exwm and xah-fly-keys and much more, big config >1000 lines, maybe it's a theme thing, with flat I see a blue line maybe color of text and background somehow the same.

Ok changed the theme and that fixed all 3, so darktooth-theme from:
https://github.com/emacsfodder/emacs-theme-darktooth

It has over 100.000 downloads in Melpa so seems pretty popular, so maybe worth to look into it.

**Comment by spiderbit** [comment]
@minad 
1. should I open up another issue about the theme or do you think it's a bug in the theme?
2. Would be very happy/thankful if you answer me if there is a way to or how to setup to execute a action from the indexed extension? Like with pressing something like f1-f2... or however the author thought to use it? Or is there no obvious way to do so, then I would wonder what the point of showing a number before the entries is?

**Comment by minad** [comment]
1. Yes, I appreciate it if you open a bug report there. Or you may even want to open a PR there? Overall I haven't found many themes with comprehensive support - if you are looking for one, I recommend the modus-themes. But they have a different style than the darktooth theme you are currently using.

2. It is actually quite obvious ;) You select the candidates using prefix arguments, e.g., C-3 RET. But you may also want to look into vertico-quick, I like this a bit more. It behaves a bit like Avy. You can bind `vertico-quick-exit` to `C-q`. Then you can submit for example by `C-q a`.

3. No, this is not a problem (theoretically...). There is the [mini-frame](https://github.com/muffinmad/emacs-mini-frame) package or my [mini-popup](https://github.com/minad/mini-popup), which is a bit simpler.  Both packages are more general than ivy-posframe since they transfer the entire minibuffer. A special vertico-posframe package does not exist (yet?), but I also don't really see a reason for it given the more general solutions. I have a bit of experience with child frames and to say the least, child frames are brittle. Since you are using EXWM, the situation is even more problematic since child frames are hidden below the X windows. For this reason posframe includes a hack which converts the child frame to an actual frame (standalone mode, I guess you use already use this with ivy-posframe?). I am not sure if mini-frame also supports such a standalone mode (My mini-popup doesn't support it). My recommendation currently is to not use child frames for the minibuffer as of now and in particular not in combination with EXWM.

**Comment by spiderbit** [comment]
Just played a bit around and looked around... A playing with veritco-buffer side to right and left makes a lot of sense for a vertical command list especially on my netbook left / right makes more sense then top buffer.
So side should be a config option, just a small thing.

posframe should be not that hard when I look over buffer extension and the ivy-posframe code...

But another thing, the flat extension is cool because I personaly only considered leaving ido/smex because of ivy-posframe otherwise I prefer horizontal views, probably because my eyes and therefor viewfield is also aligned horrizontally, therefor this flat/horrizontal mode is important for me, especially till such posframe extension exists, but to be a competitor to smex (for me) it should show 10 entries not 5.

I don't get how to reconfigure that, somehow only in flat mode it shows 5 candidates and in all other modes it shows 10.
On my 4k monitor the full line is used and on my netbook it's 2 lines but it spontanious feels more functional to me. only showing 5 entries feels a bit like holding down 1 eye :D

**Comment by minad** [comment]
> A playing with veritco-buffer side to right and left makes a lot of sense for a vertical command list especially on my netbook left / right makes more sense then top buffer. So side should be a config option, just a small thing.

Agree with that. It is configurable via `vertico-buffer-action`. But no preconfigured choice for the customize UI as of now.

> posframe should be not that hard when I look over buffer extension and the ivy-posframe code...

Yes, shouldn't be a problem to make this.

> But another thing, the flat extension is cool because I personaly only considered leaving ido/smex because of ivy-posframe otherwise I prefer horizontal views, probably because my eyes and therefor viewfield is also aligned horrizontally, therefor this flat/horrizontal mode is important for me, especially till such posframe extension exists, but to be a competitor to smex (for me) it should show 10 entries not 5.

How does ido/smex fit so many entries there? Is the view more compressed? Can you show me screenshots? vertico-flat shows as many candidates as fit. Note that amx/smex is not necessary with the Vertico/Selectrum ecosystem. It may not even work correctly. There is Marginalia for annotations and Orderless for filtering. Furthermore Vertico sorts by history position out of the box (see also https://github.com/raxod502/selectrum/wiki/Useful-packages).

> I don't get how to reconfigure that, somehow only in flat mode it shows 5 candidates and in all other modes it shows 10.
On my 4k monitor the full line is used and on my netbook it's 2 lines but it spontanious feels more functional to me. only showing 5 entries feels a bit like holding 1 eye closed, driving half blind :D

Hmm, it could be that there is an issue regarding the computation of the window/candidate width. You may want to take a closer look at the vertico-flat code to see check why it shows only so few candidates. (For me it works as expected.)

https://github.com/minad/vertico/blob/864dfeb4e98c4629d1c3e2005b1c3baa7dea7cc9/extensions/vertico-flat.el#L68-L91

> Otherwise on my netbook at least the standard command search algorythm seems a bit slow, like I type a few letters and then 2 seconds later it updates the candidates or maybe 1 sec, ido/smex is there faster.

This doesn't sound good. I am not using a high powered computer myself, but for me M-x is instantaneous. Which configuration do you use? Do you see this issue in a minimal configuration with emacs -Q? Only enable `vertico-mode` and `(setq completion-styles '(orderless)`. Nothing else. And you can even omit orderless and try only `(setq completion-styles '(basic substring)`.

But maybe you are using the `flex` completion style? This could be given that you like smex. `flex` is unfortunately not particularly efficient. I have something in the works which may improve this upstream. However I must also say that I am very happy with orderless, which brings me much quicker to the destination. Orderless also supports flex matching, but it is less valuable than flex, since it doesn't affect sorting. (Not affecting sorting is actually a feature for me ;) On the other hand, if you are accustomed to flex it may be asking a bit too much to make the move to Orderless. It should be possible to make smex/amx work with Vertico. If Icomplete and default completion works with smex/amx, then Vertico will support it too.

**Comment by spiderbit** [comment]
Yes I have basic / substring / partial-complition and flex active :D don't understand this to well yet :D, I think in ido I use flx which is different from flex if I am not wrong about this?
How does hotfuzz compare to those? Faster than flex? It should at least behave more similar to smex if I understand that correctly.

I thing I find strange when I type vert + tab, it completes veritico-mode (I think the last in history), yet there are more candidates that start with vertico obviously, why doesn't it complete to vertico and then expects more input to limit down more... doesn't make really sense to me.

I am not sure if using other limiters makes it faster but without flex it's very bad completion nothing I can work with. But I notice that with the same examples in smex all works well with vertico the cpu-fan starts :D

That is not my biggest problem, so could you give me a answer about indexed mode and how to execute Option 1,2,3,4,5? or better 0,1,2,3,4.

Btw I seen a bug when you have the buffer-mode activated to the left or right, and I complete a command with tab then delete the command and try to type again without closing it, then it cuts of the first few letters of the hits (in vertical / normal mode).

So if I complete to vertico-flat-mode with tab it shows:
ico-flat-mode

So it cuts of the vert, and when I then delete it shows all candidates without the first 4 letters, that is when I set it the buffer to right. Well it's the same with "left".

So if I change the vertico-buffer-action from top to left or right.

**Comment by spiderbit** [comment]
Well sorry you answered the index thing already... did overlook that comment.

**Comment by minad** [comment]
> I find it strange when I type vert + tab, it completes veritico-mode (I think the last in history), yet there are more candidates that start with vertico obviously, why doesn't it complete to vertico and then expects more input to limit down more... doesn't make really sense to me.

Look at the section "TAB completion" in the Vertico README. This is a long story. TAB completion usually doesn't make progress, it is different from the orderless/flex style of completing. Therefore TAB just inserts.

> Btw I seen a bug when you have the buffer-mode activated to the left or right, and I complete a command with tab then delete the command and try to type again without closing it, then it cuts of the first few letters of the hits (in vertical / normal mode).

Never seen this. Please try to create a reproducible bug report with emacs -Q and a list of instructions. Otherwise I have no chance to track this down.

**Comment by minad** [comment]
See also this long discussion regarding TAB completion: https://github.com/raxod502/selectrum/issues/272

**Comment by spiderbit** [comment]
Well C-3 doesn't work for me, there is bound previous error in the overriding-terminal-local-map.

I just tested it with emacs -Q

and it works yet I find the key coord with holding down the ctrl key so long not very good anyway, so no reason to really find out what the problem is maybe xah-fly-keys or something interferes with it.

I will give vertico-hint a try maybe that works :D 

About the bug, I will create a new bugreport for it, well just tested it in emacs -Q there it behaves "better" but still a bit buggy, when I complete to veritco-buffer-mode it shows below -buffer-mode as marked option, which is probably not ideal, but if I delete it again it resets again and I see the entries. I edited the buffer file with that 1 change, so I am sure that will not happen if the buffer is top as it's coded in the extension, except you have a command that is longer than the buffers length.

But I am not suprised you didn't see that because I am probably the first that changed the code in the buffer-extension to left/right.

I would assume the buffer get created in % of the display? so I assume it becomes only a problem with low resolution?

Well thanks for all the help, will chew on this a bit, will try out hotfuzz and miniframe/minipopup. Is the latter only working on point like a popup menu?

**Comment by minad** [comment]
> and it works yet I find the key coord with holding down the ctrl key so long not very good anyway, so no reason to really find out what the problem is maybe xah-fly-keys or something interferes with it.

As far as I know, xfk overwrites the prefix keys and reuse C-1234567890 for other purposes. Therefore it doesn't work. As I said, maybe vertico-quick is a better fit for you.

> I would assume the buffer get created in % of the display? so I assume it becomes only a problem with low resolution?

I added more display actions to choose from. Please give them a try. You can also customize this further. But I am pretty sure there is no bug here. You should customize the display action such that it works for you, this is up to the user.

> Well thanks for all the help, will chew on this a bit, will try out hotfuzz and miniframe/minipopup. Is the latter only working on point like a popup menu?

I don't recommend this. From our conversation it seems that your configuration is already quite intricate with packages interfering. I am taking a more minimalist approach where I add packages step by step and only add new packages if they don't mess with the existing setup. In principle the Vertico/Selectrum/etc packages should fit every setup since they are quite unassuming and are narrowly focused to a single purpose (e.g. Vertico only provides the UI). But still, the baseline for the design is emacs -Q. If you add other packages which change a lot (e.g. xah-fly-keys) it may require more configuration.
